###########################################################################
# Title:         Saltbox: Resources | Tasks | Instances | Get Radarr Info #
# Author(s):     salty                                                    #
# URL:           https://github.com/saltyorg/Saltbox                      #
# --                                                                      #
###########################################################################
#                   GNU General Public License v3.0                       #
###########################################################################
---
- name: Resources | Tasks | Instances | Get Info | Check if Radarr exists
  ansible.builtin.stat:
    path: "{{ radarr_paths_config_location }}"
  register: radarr_paths_config_location_stat

- name: Resources | Tasks | Instances | Get Info | Radarr API Key tasks
  block:

    - name: Resources | Tasks | Instances | Get Info | Fetch Radarr API Key
      community.general.xml:
        path: "{{ radarr_paths_config_location }}"
        xpath: /Config/ApiKey
        content: text
      register: xmlresp

    - name: Resources | Tasks | Instances | Get Info | Set 'radarr_info' variable
      ansible.builtin.set_fact:
        radarr_info: "{{ radarr_info | default({}) | combine({radarr_name: {'name': radarr_name, 'url': radarr_web_url, 'api_key': xmlresp.matches[0].ApiKey}}) }}"

  when: (radarr_paths_config_location_stat.stat.exists)

- name: Resources | Tasks | Instances | Get Info | Set 'radarr_info' variable
  ansible.builtin.set_fact:
    radarr_info: "{{ radarr_info | default({}) | combine({radarr_name: {'name': radarr_name, 'url': radarr_web_url, 'api_key': 'not installed'}}) }}"
  when: (not radarr_paths_config_location_stat.stat.exists)
