#########################################################################
# Title:         Saltbox: UnionFS | Service Tasks                       #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Services | Check if '{{ _service_file }}' exists"
  ansible.builtin.stat:
    path: "/etc/systemd/system/{{ _service_file }}"
  register: _service_file_status

- name: "Services | Tasks for '{{ _service_file }}'"
  block:

    - name: "Services | Stop and disable existing '{{ _service_file }}'"
      ansible.builtin.systemd:
        name: "{{ _service_file }}"
        state: stopped
        enabled: false
      ignore_errors: true

    - name: "Services | Update credentials in existing '{{ _service_file }}'" # noqa args[module]
      community.general.ini_file:
        path: "/etc/systemd/system/{{ _service_file }}"
        section: Service
        option: "{{ inner_item.option }}"
        value: "{{ inner_item.value }}"
        state: "{{ inner_item.state }}"
        mode: '0644'
        no_extra_spaces: true
      loop:
        - { option: 'User', value: '{{ user.name }}', state: "{{ 'absent' if (_service_file != 'mergerfs.service') else 'absent' }}" }
        - { option: 'Group', value: '{{ user.name }}', state: "{{ 'absent' if (_service_file != 'mergerfs.service') else 'absent' }}" }
      loop_control:
        loop_var: inner_item

    - name: Replace '/mnt/local' with '/mnt/feeder' in existing '{{ _service_file }}'"
      ansible.builtin.replace:
        path: "/etc/systemd/system/{{ _service_file }}"
        regexp: "\\/mnt\\/local"
        replace: '/mnt/feeder'
      when:
        - feeder_mount_is_enabled
        - (feeder_remote_is_active is defined and feeder_remote_is_active)

    - name: Replace '/mnt/feeder' with '/mnt/local' in existing '{{ _service_file }}'"
      ansible.builtin.replace:
        path: "/etc/systemd/system/{{ _service_file }}"
        regexp: "\\/mnt\\/feeder"
        replace: '/mnt/local'
      when: (not feeder_mount_is_enabled) or (not (feeder_remote_is_active is defined and feeder_remote_is_active))

    - name: "Services | Systemd daemon-reload"
      ansible.builtin.systemd:
        daemon_reload: true

  when: _service_file_status.stat.exists
