#########################################################################
# Title:         Saltbox: Sanity Check | Ansible Version                #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Find Ansible version
  ansible.builtin.shell: python3 -c 'from ansible_collections.ansible_release import ansible_version; print(ansible_version)'
  register: registered_ansible_version

- name: Print Ansible version
  ansible.builtin.debug:
    msg:
      - "Installed Ansible version: {{ registered_ansible_version.stdout }}."
      - "Installed Ansible Core version: {{ ansible_version.full }}."

- name: Check if Ansible needs upgrading
  ansible.builtin.set_fact:
    ansible_update: true
  when: (registered_ansible_version.stdout is version(sanity_check_ansible_version_min, 'lt', version_type='semver'))

- name: "Upgrade Ansible -- DO NOT CANCEL"
  ansible.builtin.script:
    cmd: /srv/git/saltbox/scripts/update.sh
  become: true
  become_user: root
  when: ansible_update

- name: "Upgrade Ansible | Check if Ansible was upgraded"
  block:

    - name: "Upgrade Ansible | Chown update log file"
      ansible.builtin.file:
        path: "/srv/git/saltbox/ansible-update.log"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: '0664'

    - name: "Upgrade Ansible | Print Instructions"
      ansible.builtin.debug:
        msg:
          - "Ansible was upgraded"
          - "You will need to re-run your previous tag."

    - name: "Upgrade Ansible | Exit"
      ansible.builtin.meta: end_play
  when: ansible_update
