#########################################################################
# Title:         Saltbox: Sanity Check | Ansible Version                #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Ansible Version | Find Ansible version
  ansible.builtin.shell: "{{ saltbox_python }} -c 'from ansible_collections.ansible_release import ansible_version; print(ansible_version)'"
  register: registered_ansible_version

- name: Ansible Version | Print Ansible version
  ansible.builtin.debug:
    msg:
      - "Installed Ansible version: {{ registered_ansible_version.stdout }}."
      - "Installed Ansible Core version: {{ ansible_version.full }}."
