##########################################################################
# Title:         Saltbox: Tautulli | Default Variables                   #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

tautulli_name: tautulli

################################
# Paths
################################

tautulli_paths_folder: "{{ tautulli_name }}"
tautulli_paths_location: "{{ server_appdata_path }}/{{ tautulli_paths_folder }}"
tautulli_paths_scripts_location: "{{ server_appdata_path }}/scripts/{{ tautulli_paths_folder }}"
tautulli_paths_folders_list:
  - "{{ tautulli_paths_location }}"
  - "{{ tautulli_paths_scripts_location }}"

################################
# Web
################################

tautulli_web_subdomain: "{{ tautulli_name }}"
tautulli_web_domain: "{{ user.domain }}"
tautulli_web_port: "8181"
tautulli_web_url: "{{ 'https://' + tautulli_web_subdomain + '.' + tautulli_web_domain
                   if (reverse_proxy_is_enabled)
                   else 'http://localhost:' + tautulli_web_port }}"

################################
# DNS
################################

tautulli_dns_record: "{{ tautulli_web_subdomain }}"
tautulli_dns_zone: "{{ tautulli_web_domain }}"
tautulli_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

tautulli_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
tautulli_traefik_middleware: "{{ traefik_default_middleware + ',' + tautulli_traefik_sso_middleware
                              if (tautulli_traefik_sso_middleware | length > 0)
                              else traefik_default_middleware }}"
tautulli_traefik_certresolver: "{{ traefik_default_certresolver }}"
tautulli_traefik_enabled: true
tautulli_traefik_api_enabled: true
tautulli_traefik_api_endpoint: "`/api`,`/newsletter`,`/image`"

################################
# THEME
################################

# Options can be found at https://github.com/gilbN/theme.park
tautulli_themepark_enabled: false
tautulli_themepark_theme: "{{ global_themepark_theme }}"
tautulli_themepark_domain: "{{ global_themepark_domain }}"

################################
# Docker
################################

# Container
tautulli_docker_container: "{{ tautulli_name }}"

# Image
tautulli_docker_image_pull: true
tautulli_docker_image_tag: "release"
tautulli_docker_image: "cr.hotio.dev/hotio/tautulli:{{ tautulli_docker_image_tag }}"

# Ports
tautulli_docker_ports_defaults:
  - "{{ tautulli_web_port }}:{{ tautulli_web_port }}"
tautulli_docker_ports_custom: []
tautulli_docker_ports: "{{ tautulli_docker_ports_defaults
                           + tautulli_docker_ports_custom
                        if (not reverse_proxy_is_enabled)
                        else [] + tautulli_docker_ports_custom }}"

# Envs
tautulli_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  UMASK: "002"
  TZ: "{{ tz }}"
  TP_DOMAIN: "{{ tautulli_themepark_domain }}"
  TP_THEME: "{{ tautulli_themepark_theme }}"
  TP_HOTIO: "true"
tautulli_docker_envs_custom: {}
tautulli_docker_envs: "{{ tautulli_docker_envs_default
                          | combine(tautulli_docker_envs_custom) }}"

# Commands
tautulli_docker_commands_default: []
tautulli_docker_commands_custom: []
tautulli_docker_commands: "{{ tautulli_docker_commands_default
                              + tautulli_docker_commands_custom }}"

# Volumes
tautulli_docker_volumes_default:
  - "{{ tautulli_paths_location }}:/config"
  - "{{ server_appdata_path }}/scripts:/scripts"
tautulli_docker_volumes_custom: []
tautulli_docker_volumes_theme:
  - "{{ tautulli_paths_location }}/98-themepark.sh:/etc/cont-init.d/98-themepark"
tautulli_docker_volumes: "{{ tautulli_docker_volumes_default
                             + tautulli_docker_volumes_custom
                             + docker_volumes_downloads_common
                          if not (tautulli_themepark_enabled)
                          else tautulli_docker_volumes_default
                             + tautulli_docker_volumes_custom
                             + docker_volumes_downloads_common
                             + tautulli_docker_volumes_theme}}"

# Devices
tautulli_docker_devices_default: []
tautulli_docker_devices_custom: []
tautulli_docker_devices: "{{ tautulli_docker_devices_default
                             + tautulli_docker_devices_custom }}"

# Hosts
tautulli_docker_hosts_default: []
tautulli_docker_hosts_custom: []
tautulli_docker_hosts: "{{ docker_hosts_common
                           | combine(tautulli_docker_hosts_default)
                           | combine(tautulli_docker_hosts_custom) }}"

# Labels
tautulli_docker_labels_default: {}
tautulli_docker_labels_custom: {}
tautulli_docker_labels: "{{ docker_labels_common
                            | combine(tautulli_docker_labels_default)
                            | combine(tautulli_docker_labels_custom) }}"

# Hostname
tautulli_docker_hostname: "{{ tautulli_name }}"

# Networks
tautulli_docker_networks_alias: "{{ tautulli_name }}"
tautulli_docker_networks_default: []
tautulli_docker_networks_custom: []
tautulli_docker_networks: "{{ docker_networks_common
                              + tautulli_docker_networks_default
                              + tautulli_docker_networks_custom }}"

# Capabilities
tautulli_docker_capabilities_default: []
tautulli_docker_capabilities_custom: []
tautulli_docker_capabilities: "{{ tautulli_docker_capabilities_default
                                  + tautulli_docker_capabilities_custom }}"

# Security Opts
tautulli_docker_security_opts_default: []
tautulli_docker_security_opts_custom: []
tautulli_docker_security_opts: "{{ tautulli_docker_security_opts_default
                                   + tautulli_docker_security_opts_custom }}"

# Restart Policy
tautulli_docker_restart_policy: unless-stopped

# State
tautulli_docker_state: started
