#########################################################################
# Title:         Saltbox: Jellyfin - Post-Install Tasks                 #
# Author(s):     kowalski, desimaniac, owine                            #
# URL:           https://github.com/saltyorg/Saltbox                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Wait 10 seconds before continuing
  ansible.builtin.wait_for:
    timeout: 10

- name: Post-Install | Ensure transcodes folder has the correct permissions
  ansible.builtin.file:
    path: "{{ jellyfin_paths_transcodes_location }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    recurse: true

- name: Post-Install | Ensure config folder has the correct permissions
  ansible.builtin.file:
    path: "{{ jellyfin_paths_location }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    recurse: true

- name: Post-Install | Settings Tasks
  ansible.builtin.import_tasks: "settings.yml"
  when: (not jellyfin_existing_install.stat.exists)
