#########################################################################
# Title:         Saltbox: Cloudflare | Page Rules | Remove Page Rule    #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Page Rules | Remove Page Rule | Remove Previous Cloudflare Page Rules for Lets Encrypt
  ansible.builtin.uri:
    url: 'https://api.cloudflare.com/client/v4/zones/{{ cloudflare_zone }}/pagerules/{{ item }}'
    method: DELETE
    headers:
      Content-Type: "application/json"
      X-Auth-Email: '{{ cloudflare.email }}'
      X-Auth-Key: '{{ cloudflare.api }}'
    return_content: true
  loop: "{{ cloudflare_page_rules }}"
  register: cf_page_rule_destruction

- name: Page Rules | Remove Page Rule | Print result of Lets Encrypt Cloudflare Page Rule Destruction
  ansible.builtin.debug:
    msg: "Successfully deleted Let's Encrypt Cloudflare page rule for '{{ fld.stdout }}'"
  when: (cf_page_rule_destruction.results[0].json.success is defined) and cf_page_rule_destruction.results[0].json.success
