##########################################################################
# Title:         Saltbox: Sonarr | Post-Install | Update Ports           #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Post-Install | Update Ports | Wait for '{{ sonarr_paths_config_location | basename }}' to be created
  ansible.builtin.wait_for:
    path: "{{ sonarr_paths_config_location }}"
    state: present

- name: Post-Install | Update Ports | Find external port binding for '{{ sonarr_docker_container }}' docker port '{{ sonarr_web_port }}'
  block:

    - name: Post-Install | Update Ports | Lookup host port mapped to '{{ sonarr_docker_container }}' docker port '{{ sonarr_web_port }}'
      ansible.builtin.shell:
        docker port {{ sonarr_docker_container }} {{ sonarr_web_port }} | 2> /dev/null | sed 's/[0-9.]*://'
      register: sonarr_docker_port_lookup_cmd
      changed_when: false

    - name: Post-Install | Update Ports | Set port variable
      ansible.builtin.set_fact:
        sonarr_docker_port_lookup: >-
          {{ (sonarr_docker_port_lookup_cmd.stdout | trim)
              if (sonarr_docker_port_lookup_cmd.stdout | trim | length > 0)
              else sonarr_web_port }}

  when: not reverse_proxy_is_enabled

- name: Post-Install | Update Ports | Update 'Port' in '{{ sonarr_paths_config_location | basename }}'
  community.general.xml:
    path: "{{ sonarr_paths_config_location }}"
    xpath: /Config/Port
    value: "{{ sonarr_docker_port_lookup | default(sonarr_web_port) }}"
    state: present
  become: true
  become_user: "{{ user.name }}"
  ignore_errors: true
  register: sonarr_port_update

- name: Post-Install | Update Ports | Reset permissions of '{{ sonarr_paths_config_location | basename }}'
  ansible.builtin.file:
    path: "{{ sonarr_paths_config_location }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
  when: sonarr_port_update is changed
