#########################################################################
# Title:         Saltbox: Whisparr Role                                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Whisparr roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    whisparr_name: "{{ role }}"
  with_items: "{{ whisparr_instances }}"
  loop_control:
    loop_var: role
