##########################################################################
# Title:         Saltbox: Cloudplow | Default Variables                  #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Name
################################

cloudplow_name: cloudplow

################################
# Settings
################################

# Default for all remotes.
cloudplow_remote_default_folder: "/Media"

# To change the folder for a specific remote:
# cloudplow_remote_movies_folder: "/Media/Movies"
# cloudplow_remote_dropbox_folder: "Media"
# cloudplow_remote_nameofremote_folder: "targetfolder"

################################
# Paths
################################

cloudplow_folder: "{{ cloudplow_name }}"

cloudplow_path: "{{ server_appdata_path }}/{{ cloudplow_folder }}"

cloudplow_venv_path: "{{ cloudplow_path }}/venv"

cloudplow_python_path: "{{ cloudplow_bin_folder }}/python3"

cloudplow_script_path: "{{ cloudplow_path }}/cloudplow.py"

cloudplow_requirements_path: "{{ cloudplow_path }}/requirements.txt"

cloudplow_config_path: "{{ cloudplow_path }}/config.json"

cloudplow_alias_path: "/usr/local/bin/{{ cloudplow_name }}"

################################
# GitHub Repository
################################

cloudplow_git_repo_url: "https://github.com/l3uddz/cloudplow.git"

cloudplow_git_repo_dest: "{{ cloudplow_path }}"

cloudplow_git_repo_branch_primary: "master"

cloudplow_git_repo_branch_secondary: "develop"

################################
# Systemd
################################

cloudplow_service_name: "{{ cloudplow_name }}"

################################
# Rclone
################################

rclone_config_path: "/home/{{ user.name }}/.config/rclone/rclone.conf"

rclone_binary_path: "/usr/bin/rclone"

cloudplow_rclone_google_template: |-
  "--user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
  "--checkers": 16,
  "--drive-chunk-size": "128M",
  "--stats": "60s",
  "--transfers": 8,
  "--verbose": 1,
  "--skip-links": null,
  "--retries": 1,
  "--low-level-retries": 2,
  "--drive-stop-on-upload-limit": null

cloudplow_rclone_dropbox_template: |-
  "--user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
  "--checkers": 16,
  "--dropbox-chunk-size": "128M",
  "--dropbox-pacer-min-sleep": "85ms",
  "--stats": "60s",
  "--transfers": 8,
  "--verbose": 1,
  "--skip-links": null,
  "--retries": 1,
  "--low-level-retries": 2

################################
# Filter variables
################################

cloudplow_remotes: []
cloudplow_upload_paths_unique: []
