##########################################################################
# Title:         Saltbox: Plex DB | Default Variables                    #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
plex_db_files:
  - "com.plexapp.plugins.library.db"
  - "com.plexapp.plugins.library.blobs.db"

plex_db_integrity_check_only: false
plex_db_failed_integrity: false
plex_db_failed_optimization: false
