##########################################################################
# Title:         Saltbox: Plex Auth Token | Default Variables            #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# API
################################

plex_auth_token_version: "1.0.0"
plex_auth_token_product: "Saltbox"
plex_auth_token_platform: "Linux"
plex_auth_token_platform_version: "1.0.0"
plex_auth_token_device: "Ubuntu {{ ansible_distribution_version }} - {{ ansible_kernel }}"
plex_auth_token_device_name: "Saltbox"
