#########################################################################
# Title:         Saltbox: Jellyfin | Default Variables                  #
# Author(s):     kowalski, desimaniac, owine                           #
# URL:           https://github.com/saltyorg/Saltbox                   #
# --                                                                   #
#########################################################################
#                   GNU General Public License v3.0                    #
#########################################################################
---
################################
# Basics
################################

jellyfin_instances: ["jellyfin"]

################################
# Settings
################################

# System
jellyfin_role_system_settings_public_port: "80"
jellyfin_role_system_settings_public_https_port: "443"
jellyfin_role_system_settings_enable_folder_view: "true"
jellyfin_role_system_settings_quick_connect_available: "true"
jellyfin_role_system_settings_enable_remote_access: "true"
jellyfin_role_system_settings_server_name: "saltbox"

# Network
jellyfin_role_network_settings_public_https_port: "443"
jellyfin_role_network_settings_known_proxies:
  - traefik
jellyfin_role_network_settings_published_server_uri_by_subnet:
  - "external={{ lookup('role_var', '_web_url', role='jellyfin') }}:443"

################################
# Paths
################################

jellyfin_role_paths_folder: "{{ jellyfin_name }}"
jellyfin_role_paths_location: "{{ server_appdata_path }}/{{ jellyfin_role_paths_folder }}"
jellyfin_role_paths_transcodes_location: "{{ transcodes_path }}/{{ jellyfin_role_paths_folder }}"
jellyfin_role_paths_folders_list:
  - "{{ jellyfin_role_paths_location }}"
  - "{{ jellyfin_role_paths_location }}/data"
  - "{{ jellyfin_role_paths_location }}/log"
  - "{{ jellyfin_role_paths_location }}/cache"
  - "{{ jellyfin_role_paths_transcodes_location }}"
jellyfin_role_paths_dlna_location: "{{ jellyfin_role_paths_location }}/dlna.xml"
jellyfin_role_paths_sys_xml_location: "{{ jellyfin_role_paths_location }}/system.xml"
jellyfin_role_paths_net_xml_location: "{{ jellyfin_role_paths_location }}/network.xml"
jellyfin_role_paths_xml_location_old: "{{ jellyfin_role_paths_location }}/app/config/system.xml"

################################
# Web
################################

jellyfin_role_web_subdomain: "{{ jellyfin_name }}"
jellyfin_role_web_domain: "{{ user.domain }}"
jellyfin_role_web_port: "8096"
jellyfin_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='jellyfin') + '.' + lookup('role_var', '_web_domain', role='jellyfin')
                        if (lookup('role_var', '_web_subdomain', role='jellyfin') | length > 0)
                        else lookup('role_var', '_web_domain', role='jellyfin')) }}"

################################
# DNS
################################

jellyfin_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='jellyfin') }}"
jellyfin_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='jellyfin') }}"
jellyfin_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

jellyfin_role_traefik_sso_middleware: ""
jellyfin_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
jellyfin_role_traefik_middleware_custom: ""
jellyfin_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
jellyfin_role_traefik_enabled: true
jellyfin_role_traefik_api_enabled: false
jellyfin_role_traefik_api_endpoint: ""
jellyfin_role_traefik_gzip_enabled: false

################################
# Config
################################

jellyfin_role_system_settings_default:
  - xpath: 'PublicPort'
    value: "{{ lookup('role_var', '_system_settings_public_port', role='jellyfin') }}"
  - xpath: 'PublicHttpsPort'
    value: "{{ lookup('role_var', '_system_settings_public_https_port', role='jellyfin') }}"
  - xpath: 'EnableFolderView'
    value: "{{ lookup('role_var', '_system_settings_enable_folder_view', role='jellyfin') }}"
  - xpath: 'QuickConnectAvailable'
    value: "{{ lookup('role_var', '_system_settings_quick_connect_available', role='jellyfin') }}"
  - xpath: 'EnableRemoteAccess'
    value: "{{ lookup('role_var', '_system_settings_enable_remote_access', role='jellyfin') }}"
  - xpath: 'ServerName'
    value: "{{ lookup('role_var', '_system_settings_server_name', role='jellyfin') }}"
jellyfin_role_system_settings_custom: []
jellyfin_role_system_settings_list: "{{ lookup('role_var', '_system_settings_default', role='jellyfin') + lookup('role_var', '_system_settings_custom', role='jellyfin') }}"

jellyfin_role_network_settings_default:
  - xpath: 'PublicHttpsPort'
    value: "{{ lookup('role_var', '_network_settings_public_https_port', role='jellyfin') }}"
  - xpath: 'KnownProxies'
    set_children: "{{ lookup('role_var', '_network_settings_known_proxies', role='jellyfin') | map('community.general.dict_kv', 'string') | list }}"
  - xpath: 'PublishedServerUriBySubnet'
    set_children: "{{ lookup('role_var', '_network_settings_published_server_uri_by_subnet', role='jellyfin') | map('community.general.dict_kv', 'string') | list }}"
jellyfin_role_network_settings_custom: []
jellyfin_role_network_settings_list: "{{ lookup('role_var', '_network_settings_default', role='jellyfin') + lookup('role_var', '_network_settings_custom', role='jellyfin') }}"

################################
# Docker
################################

# Container
jellyfin_role_docker_container: "{{ jellyfin_name }}"

# Image
jellyfin_role_docker_image_pull: true
jellyfin_role_docker_image_repo: "ghcr.io/hotio/jellyfin"
jellyfin_role_docker_image_tag: "release"
jellyfin_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='jellyfin') }}:{{ lookup('role_var', '_docker_image_tag', role='jellyfin') }}"

# Envs
jellyfin_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  DOTNET_USE_POLLING_FILE_WATCHER: "1"
jellyfin_role_docker_envs_custom: {}
jellyfin_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='jellyfin')
                               | combine(lookup('role_var', '_docker_envs_custom', role='jellyfin')) }}"

# Volumes
jellyfin_role_docker_volumes_default:
  - "{{ jellyfin_role_paths_location }}:/config:rw"
  - "{{ server_appdata_path }}/scripts:/scripts"
  - "/dev/shm:/dev/shm"
  - "{{ jellyfin_role_paths_transcodes_location }}:/transcode"
jellyfin_role_docker_volumes_legacy:
  - "/mnt/unionfs/Media:/data"
jellyfin_role_docker_volumes_custom: []
jellyfin_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='jellyfin')
                                  + lookup('role_var', '_docker_volumes_custom', role='jellyfin')
                                  + (lookup('role_var', '_docker_volumes_legacy', role='jellyfin')
                                    if docker_legacy_volume
                                    else []) }}"

# Mounts
jellyfin_role_docker_mounts_default:
  - target: /tmp
    type: tmpfs
jellyfin_role_docker_mounts_custom: []
jellyfin_role_docker_mounts: "{{ lookup('role_var', '_docker_mounts_default', role='jellyfin')
                                 + lookup('role_var', '_docker_mounts_custom', role='jellyfin') }}"

# Hostname
jellyfin_role_docker_hostname: "{{ jellyfin_name }}"

# Networks
jellyfin_role_docker_networks_alias: "{{ jellyfin_name }}"
jellyfin_role_docker_networks_default: []
jellyfin_role_docker_networks_custom: []
jellyfin_role_docker_networks: "{{ docker_networks_common
                                   + lookup('role_var', '_docker_networks_default', role='jellyfin')
                                   + lookup('role_var', '_docker_networks_custom', role='jellyfin') }}"

# Restart Policy
jellyfin_role_docker_restart_policy: unless-stopped

# State
jellyfin_role_docker_state: started
