##########################################################################
# Title:         Saltbox: MOTD | Default Variables                       #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
motd_install: true

# Requires the new golang CLI to be installed and in the location set below
# if you set motd_use_python to false.
motd_use_python: true
motd_cli_path: "/usr/local/bin/sb"
motd_cli_flags: "--all --title 'Saltbox' --font ivrit --type parchment"
