#########################################################################
# Title:         Saltbox: Netdata Role                                  #
# Author(s):     desimaniac, l3uddz, salty                              #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"

- name: Create Docker Socket Proxy container
  include_role:
    name: docker_socket_proxy

- name: Remove existing Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Settings Task
  import_tasks: "subtasks/settings.yml"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: Create Netdata volumes
  docker_volume:
    name: "{{ item }}"
  with_items:
    - netdatalib
    - netdatacache

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
