#########################################################################
# Title:         Saltbox: Nvidia | Patch Tasks                          #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Patch | Download Nvidia patch
  ansible.builtin.get_url:
    url: "{{ nvidia_patch_download_url }}"
    dest: "{{ nvidia_patch_download_dest }}"
    mode: 0775
    owner: root
    group: root
    force: true
    validate_certs: false
  register: x
  until: "x is not failed"
  retries: 5
  delay: 10

- name: Patch | Install Nvidia patch
  ansible.builtin.shell: "{{ nvidia_patch_download_dest }}"
  args:
    executable: /bin/bash
  register: patch_install
  ignore_errors: true

- name: Patch | Nvidia patch installed
  ansible.builtin.debug:
    msg: "Nvidia patch installed!"
  when: (patch_install is succeeded) and ('Patched!' in patch_install.stdout)

- name: Patch | Nvidia patch did not install
  ansible.builtin.fail:
    msg:
      - "Nvidia patch did not install!"
      - "{{ patch_install.stdout }}"
  when: (patch_install is failed) or ('Patched!' not in patch_install.stdout)
