#########################################################################
# Title:         Saltbox: Trackarr | Pre-Install Tasks                  #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Pre-Install | Check if Trackarr config exists
  ansible.builtin.stat:
    path: "{{ trackarr_paths_config_location }}"
  register: trackarr_paths_config_location_stat

- name: Pre-Install | New Trackarr config tasks
  block:

    - name: Pre-Install | Get Instance Info
      ansible.builtin.include_tasks: "{{ resources_tasks_path }}/instances/get_info.yml"

    - name: Pre-Install | Set 'trackarr_server_apikey' variable
      ansible.builtin.set_fact:
        trackarr_server_apikey: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=22') }}"

    - name: Pre-Install | Import default Trackarr config
      ansible.builtin.template:
        src: "config.yaml.j2"
        dest: "{{ trackarr_paths_config_location }}"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0775"
        force: false

    - name: Pre-Install | Set 'trackarr_docker_state' variable
      ansible.builtin.set_fact:
        trackarr_docker_state: "stopped"

  when: not trackarr_paths_config_location_stat.stat.exists
