#########################################################################
# Title:         Saltbox: Shell | Default Variables                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

shell_type: "{{ shell | default('zsh') }}"
shell_editor: "nano"

################################
# Misc
################################

shell_misc_argcomplete_pip_package: argcomplete
shell_misc_argcomplete_command: "activate-global-python-argcomplete"

################################
# z (jump around)
################################

shell_z_git_repo_url: "https://github.com/rupa/z.git"
shell_z_git_repo_dest: "/opt/z"

################################
# Bash
################################

shell_bash_bashrc_path: "/home/{{ user.name }}/.bashrc"

shell_bash_bashrc_block_content: |
  # Editor
  export EDITOR={{ shell_editor }}
  # Include Z
  . /opt/z/z.sh
  # Aliases
  alias lso="ls -alG | awk '{k=0;for(i=0;i<=8;i++)k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(\" %0o \",k);print}'"
  # OSC 1337 - Set current directory
  export PS1="$PS1\[\e]1337;CurrentDir="'$(pwd)\a\]'

shell_bash_bashrc_block_custom: ""
shell_bash_binary_path: "/bin/bash"

################################
# Zsh
################################

shell_zsh_apt_packages_list:
  - zsh

shell_zsh_omzsh_git_repo_url: https://github.com/robbyrussell/oh-my-zsh.git
shell_zsh_omzsh_git_repo_dest: "/home/{{ user.name }}/.oh-my-zsh"
shell_zsh_zshrc_template_path: "/home/{{ user.name }}/.oh-my-zsh/templates/zshrc.zsh-template"
shell_zsh_zshrc_path: "/home/{{ user.name }}/.zshrc"

shell_zsh_zshrc_block_content1: |
  # Oh-my-zsh - auto update zsh without prompt
  DISABLE_UPDATE_PROMPT=true

shell_zsh_zshrc_block_content2: |
  # zsh - allows commmands to run with the un-expanded glob
  unsetopt nomatch
  # zsh - set TIMEFMT
  export TIMEFMT=$'
  real	%E
  user	%U
  sys	%S'
  # Editor
  export EDITOR={{ shell_editor }}
  # Include Z
  . /opt/z/z.sh
  # Aliases
  alias lso="ls -alG | awk '{k=0;for(i=0;i<=8;i++)k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(\" %0o \",k);print}'"
  # Load compinit and bashcompinit
  autoload -U +X compinit && compinit
  autoload -U +X bashcompinit && bashcompinit
  # OSC 1337 - Set current directory
  precmd () { echo -n "\x1b]1337;CurrentDir=$(pwd)\x07" }

shell_zsh_zshrc_block_custom: ""
shell_zsh_plugins: "(git docker docker-compose ansible)"
shell_zsh_binary_previous_path: "/bin/zsh5"
shell_zsh_binary_path: "/bin/zsh"

################################
# Oh My Posh
################################

shell_ohmyposh_enabled: false
# Takes a file path or url to a config file
shell_ohmyposh_config: ""

shell_zsh_zshrc_oh_my_posh: |
  # Oh My Posh
  eval "$(oh-my-posh init zsh{{ ' --config ' + shell_ohmyposh_config if shell_ohmyposh_config | length > 0 else '' }})"
