##########################################################################
# Title:         Saltbox: NZBHydra2 | Post-Install Tasks                 #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Post-Install | Check if SABnzbd config exists
  ansible.builtin.stat:
    path: "{{ lookup('role_var', '_paths_config_location', role='sabnzbd') }}"
  register: nzbhydra2_sabnzbd_yml_stat

- name: Post-Install | SABnzbd tasks
  ansible.builtin.include_tasks: "subtasks/post-install/sabnzbd.yml"
  when: (not nzbhydra2_yml_stat.stat.exists) and nzbhydra2_sabnzbd_yml_stat.stat.exists

- name: Post-Install | Settings Tweaks
  ansible.builtin.include_tasks: "subtasks/post-install/settings.yml"
  when: (not nzbhydra2_yml_stat.stat.exists)
