##########################################################################
# Title:         Saltbox: Jackett | Default Variables                    #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

jackett_name: jackett

################################
# Paths
################################

jackett_paths_folder: "{{ jackett_name }}"
jackett_paths_location: "{{ server_appdata_path }}/{{ jackett_paths_folder }}"
jackett_paths_folders_list:
  - "{{ jackett_paths_location }}"

################################
# Web
################################

jackett_web_subdomain: "{{ jackett_name }}"
jackett_web_domain: "{{ user.domain }}"
jackett_web_port: "9117"
jackett_web_url: "{{ 'https://' + (jackett_web_subdomain + '.' + jackett_web_domain
                  if (jackett_web_subdomain | length > 0)
                  else jackett_web_domain) }}"

################################
# DNS
################################

jackett_dns_record: "{{ jackett_web_subdomain }}"
jackett_dns_zone: "{{ jackett_web_domain }}"
jackett_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

jackett_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
jackett_traefik_middleware_default: "{{ traefik_default_middleware }}"
jackett_traefik_middleware_custom: ""
jackett_traefik_certresolver: "{{ traefik_default_certresolver }}"
jackett_traefik_enabled: true
jackett_traefik_api_enabled: true
jackett_traefik_api_endpoint: "PathPrefix(`/api`) || PathPrefix(`/dl`)"

################################
# THEME
################################

# Options can be found at https://github.com/themepark-dev/theme.park
jackett_themepark_enabled: false
jackett_themepark_theme: "{{ global_themepark_theme }}"
jackett_themepark_domain: "{{ global_themepark_domain }}"

################################
# Docker
################################

# Container
jackett_docker_container: "{{ jackett_name }}"

# Image
jackett_docker_image_pull: true
jackett_docker_image_tag: "release"
jackett_docker_image: "ghcr.io/hotio/jackett:{{ jackett_docker_image_tag }}"

# Ports
jackett_docker_ports_defaults: []
jackett_docker_ports_custom: []
jackett_docker_ports: "{{ jackett_docker_ports_defaults
                          + jackett_docker_ports_custom }}"

# Envs
jackett_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  UMASK: "002"
  TZ: "{{ tz }}"
  TP_DOMAIN: "{{ jackett_themepark_domain }}"
  TP_THEME: "{{ jackett_themepark_theme }}"
  TP_HOTIO: "true"
jackett_docker_envs_custom: {}
jackett_docker_envs: "{{ jackett_docker_envs_default
                         | combine(jackett_docker_envs_custom) }}"

# Commands
jackett_docker_commands_default: []
jackett_docker_commands_custom: []
jackett_docker_commands: "{{ jackett_docker_commands_default
                             + jackett_docker_commands_custom }}"

# Volumes
jackett_docker_volumes_default:
  - "{{ jackett_paths_location }}:/config"
jackett_docker_volumes_custom: []
jackett_docker_volumes_theme:
  - "{{ jackett_paths_location }}/98-themepark:/etc/cont-init.d/98-themepark"
jackett_docker_volumes: "{{ jackett_docker_volumes_default
                            + jackett_docker_volumes_custom
                         if not (jackett_themepark_enabled)
                         else jackett_docker_volumes_default
                            + jackett_docker_volumes_custom
                            + jackett_docker_volumes_theme }}"

# Devices
jackett_docker_devices_default: []
jackett_docker_devices_custom: []
jackett_docker_devices: "{{ jackett_docker_devices_default
                            + jackett_docker_devices_custom }}"

# Hosts
jackett_docker_hosts_default: []
jackett_docker_hosts_custom: []
jackett_docker_hosts: "{{ docker_hosts_common
                          | combine(jackett_docker_hosts_default)
                          | combine(jackett_docker_hosts_custom) }}"

# Labels
jackett_docker_labels_default: {}
jackett_docker_labels_custom: {}
jackett_docker_labels: "{{ docker_labels_common
                           | combine(jackett_docker_labels_default)
                           | combine(jackett_docker_labels_custom) }}"

# Hostname
jackett_docker_hostname: "{{ jackett_name }}"

# Networks
jackett_docker_networks_alias: "{{ jackett_name }}"
jackett_docker_networks_default: []
jackett_docker_networks_custom: []
jackett_docker_networks: "{{ docker_networks_common
                             + jackett_docker_networks_default
                             + jackett_docker_networks_custom }}"

# Capabilities
jackett_docker_capabilities_default: []
jackett_docker_capabilities_custom: []
jackett_docker_capabilities: "{{ jackett_docker_capabilities_default
                                 + jackett_docker_capabilities_custom }}"

# Security Opts
jackett_docker_security_opts_default: []
jackett_docker_security_opts_custom: []
jackett_docker_security_opts: "{{ jackett_docker_security_opts_default
                                  + jackett_docker_security_opts_custom }}"

# Restart Policy
jackett_docker_restart_policy: unless-stopped

# State
jackett_docker_state: started
