#########################################################################
# Title:         Cloudbox: Node.js                                      #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox2/cloudbox                  #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Node.js Tasks
  import_tasks: subtasks/nodejs.yml

- name: NPM Tasks
  import_tasks: subtasks/npm.yml

- name: Frontail Tasks
  import_tasks: subtasks/frontail.yml

- name: Hastebin Tasks
  import_tasks: subtasks/hastebin.yml