#########################################################################
# Title:         Saltbox: ruTorrent | Default Variables                 #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

rutorrent_name: rutorrent

################################
# Paths
################################

rutorrent_role_paths_folder: "{{ rutorrent_name }}"
rutorrent_role_paths_location: "{{ server_appdata_path }}/{{ rutorrent_role_paths_folder }}"
rutorrent_role_paths_downloads_location: "{{ downloads_torrents_path }}/{{ rutorrent_role_paths_folder }}"
rutorrent_role_paths_config_php_location: "{{ rutorrent_role_paths_location }}/rutorrent/settings/config.php"
rutorrent_role_paths_rtorrent_rc_location: "{{ rutorrent_role_paths_location }}/rtorrent/rtorrent.rc"
rutorrent_role_paths_php_local_ini_location: "{{ rutorrent_role_paths_location }}/php/php-local.ini"
rutorrent_role_paths_plugins_ini_location: "{{ rutorrent_role_paths_location }}/rutorrent/settings/plugins.ini"
rutorrent_role_paths_folders_list:
  - "{{ rutorrent_role_paths_location }}"
  - "{{ rutorrent_role_paths_location }}/plugins"
  - "{{ rutorrent_role_paths_location }}/themes"
  - "{{ rutorrent_role_paths_downloads_location }}"
  - "{{ rutorrent_role_paths_downloads_location }}/completed"
  - "{{ rutorrent_role_paths_downloads_location }}/incoming"
  - "{{ rutorrent_role_paths_downloads_location }}/watched"

################################
# Web
################################

rutorrent_role_web_subdomain: "{{ rutorrent_name }}"
rutorrent_role_web_domain: "{{ user.domain }}"
rutorrent_role_web_port: "80"
rutorrent_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='rutorrent') + '.' + lookup('role_var', '_web_domain', role='rutorrent')
                         if (lookup('role_var', '_web_subdomain', role='rutorrent') | length > 0)
                         else lookup('role_var', '_web_domain', role='rutorrent')) }}"

################################
# DNS
################################

rutorrent_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='rutorrent') }}"
rutorrent_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='rutorrent') }}"
rutorrent_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

rutorrent_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
rutorrent_role_traefik_middleware_default: "{{ traefik_default_middleware
                                               + (',themepark-' + rutorrent_name
                                                 if (lookup('role_var', '_themepark_enabled', role='rutorrent') and global_themepark_plugin_enabled)
                                                 else '') }}"
rutorrent_role_traefik_middleware_custom: ""
rutorrent_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
rutorrent_role_traefik_enabled: true
rutorrent_role_traefik_api_enabled: true
rutorrent_role_traefik_api_middleware: "rutorrent-auth,{{ traefik_default_middleware_api }}"
rutorrent_role_traefik_api_endpoint: "PathPrefix(`/RPC2`)"

################################
# Config
################################

# Toggles if public tracker functionality is enabled
rutorrent_role_config_public_trackers: false
# Path used by the diskspace plugin to check usage
rutorrent_role_config_diskspace_path: "/mnt"

## New Installs

# rtorrent.rc
rutorrent_role_config_new_installs_rutorrent_rc_settings_default:
  # Minimum number of peers to connect to per torrent
  - { option: "throttle.min_peers.normal.set", value: "1" }
  # Maximum number of simultaneous upload slots per torrent
  - { option: "throttle.max_uploads.set", value: "1024" }
  # Maximum number of simultaneous download slots, globally
  - { option: "throttle.max_downloads.global.set", value: "1024" }
  # Maximum number of simultaneous upload slots, globally
  - { option: "throttle.max_uploads.global.set", value: "1024" }
  # Maximum download rate, globally (KiB); 0 = unlimited
  - { option: "throttle.global_down.max_rate.set_kb", value: "0" }
  # Maximum upload rate, globally (KiB); 0 = unlimited
  - { option: "throttle.global_up.max_rate.set_kb", value: "0" }
  # Maximum number of open files
  - { option: "network.max_open_files.set", value: "1024" }
  # Maximum XMLRPC payloads
  - { option: "network.xmlrpc.size_limit.set", value: "20M" }
  # Encryption Parameters
  - { option: "protocol.encryption.set", value: "allow_incoming,try_outgoing,enable_retry,prefer_plaintext" }
  # Hash check on completion - disabled
  - { option: "pieces.hash.on_completion.set", value: "no" }
  # Disk space allocation - disabled
  - { option: "system.file.allocate.set", value: "0" }
  # Download Directory
  - { option: "directory.default.set", value: "/mnt/unionfs/downloads/torrents/rutorrent/completed" }
  # Watched Directory
  - { option: "schedule", value: 'watch_directory,5,5,"load.start=/mnt/unionfs/downloads/torrents/rutorrent/watched/*.torrent,d.delete_tied="' }
rutorrent_role_config_new_installs_rutorrent_rc_settings_custom: []
rutorrent_role_config_new_installs_rutorrent_rc_settings_list: "{{ lookup('role_var', '_config_new_installs_rutorrent_rc_settings_default', role='rutorrent')
                                                                   + lookup('role_var', '_config_new_installs_rutorrent_rc_settings_custom', role='rutorrent') }}"

# php-local.ini
rutorrent_role_config_new_installs_php_local_ini_settings_default:
  # Maximum Upload File Size via Web Browser (eg Uploading Torrent Files)
  - { option: "upload_max_filesize", value: "20M" }
rutorrent_role_config_new_installs_php_local_ini_settings_custom: []
rutorrent_role_config_new_installs_php_local_ini_settings_list: "{{ lookup('role_var', '_config_new_installs_php_local_ini_settings_default', role='rutorrent')
                                                                    + lookup('role_var', '_config_new_installs_php_local_ini_settings_custom', role='rutorrent') }}"

## Existing Installs

# rtorrent.rc
rutorrent_role_config_existing_installs_rutorrent_rc_settings_default:
  # Execute - Initiate Plugins
  - { option: "execute", value: "{sh,-c,/usr/bin/php /app/rutorrent/php/initplugins.php abc &}" }
  # IP address that is reported to the tracker
  - { option: "network.local_address.set", value: "{{ ip_address_public }}" }
  # Ports
  - { option: "network.port_range.set", value: "{{ rutorrent_role_docker_ports_51413 }}-{{ rutorrent_role_docker_ports_51413 }}" }
  - { option: "dht.port.set", value: "{{ rutorrent_role_docker_ports_6881 }}" }
  # Enable / Disable Public Trackers
  - { option: "dht.mode.set", value: "{{ lookup('role_var', '_config_public_trackers', role='rutorrent') | ternary('on', 'disable') }}" }
  - { option: "trackers.use_udp.set", value: "{{ lookup('role_var', '_config_public_trackers', role='rutorrent') | ternary('yes', 'no') }}" }
  - { option: "protocol.pex.set", value: "{{ lookup('role_var', '_config_public_trackers', role='rutorrent') | ternary('yes', 'no') }}" }
rutorrent_role_config_existing_installs_rutorrent_rc_settings_custom: []
rutorrent_role_config_existing_installs_rutorrent_rc_settings_list: "{{ lookup('role_var', '_config_existing_installs_rutorrent_rc_settings_default', role='rutorrent')
                                                                        + lookup('role_var', '_config_existing_installs_rutorrent_rc_settings_custom', role='rutorrent') }}"

################################
# Theme
################################

# Options can be found at https://github.com/themepark-dev/theme.park
rutorrent_role_themepark_enabled: false
rutorrent_role_themepark_app: "rutorrent"
rutorrent_role_themepark_theme: "{{ global_themepark_theme }}"
rutorrent_role_themepark_domain: "{{ global_themepark_domain }}"
rutorrent_role_themepark_addons: []

################################
# Docker
################################

# Container
rutorrent_role_docker_container: "{{ rutorrent_name }}"

# Image
rutorrent_role_docker_image_pull: true
rutorrent_role_docker_image_tag: "latest"
rutorrent_role_docker_image_repo: "kudeta/ru-rtorrent"
rutorrent_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='rutorrent') }}:{{ lookup('role_var', '_docker_image_tag', role='rutorrent') }}"

# Ports
rutorrent_role_docker_ports_51413: "{{ port_lookup_51413.meta.port
                                    if (port_lookup_51413.meta.port is defined) and (port_lookup_51413.meta.port | trim | length > 0)
                                    else '51413' }}"
rutorrent_role_docker_ports_6881: "{{ port_lookup_6881.meta.port
                                   if (port_lookup_6881.meta.port is defined) and (port_lookup_6881.meta.port | trim | length > 0)
                                   else '6881' }}"

rutorrent_role_docker_ports_default:
  - "{{ lookup('role_var', '_docker_ports_51413', role='rutorrent') }}:{{ lookup('role_var', '_docker_ports_51413', role='rutorrent') }}"
  - "{{ lookup('role_var', '_docker_ports_51413', role='rutorrent') }}:{{ lookup('role_var', '_docker_ports_51413', role='rutorrent') }}/udp"
  - "{{ lookup('role_var', '_docker_ports_6881', role='rutorrent') }}:{{ lookup('role_var', '_docker_ports_6881', role='rutorrent') }}/udp"
rutorrent_role_docker_ports_custom: []
rutorrent_role_docker_ports: "{{ lookup('role_var', '_docker_ports_default', role='rutorrent')
                                 + lookup('role_var', '_docker_ports_custom', role='rutorrent') }}"

# Envs
rutorrent_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
rutorrent_role_docker_envs_custom: {}
rutorrent_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='rutorrent')
                                | combine(lookup('role_var', '_docker_envs_custom', role='rutorrent')) }}"

# Volumes
rutorrent_role_docker_volumes_default:
  - "{{ rutorrent_role_paths_location }}:/config"
  - "{{ server_appdata_path }}/scripts:/scripts"
rutorrent_role_docker_volumes_custom: []
rutorrent_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='rutorrent')
                                   + lookup('role_var', '_docker_volumes_custom', role='rutorrent') }}"

# Labels
rutorrent_role_docker_labels_default:
  traefik.http.middlewares.rutorrent-auth.basicauth.usersfile: "/etc/traefik/auth"
rutorrent_role_docker_labels_custom: {}
rutorrent_role_docker_labels: "{{ lookup('role_var', '_docker_labels_default', role='rutorrent')
                                  | combine((traefik_themepark_labels
                                            if (lookup('role_var', '_themepark_enabled', role='rutorrent') and global_themepark_plugin_enabled)
                                            else {}),
                                            lookup('role_var', '_docker_labels_custom', role='rutorrent')) }}"

# Hostname
rutorrent_role_docker_hostname: "{{ rutorrent_name }}"

# Networks
rutorrent_role_docker_networks_alias: "{{ rutorrent_name }}"
rutorrent_role_docker_networks_default: []
rutorrent_role_docker_networks_custom: []
rutorrent_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='rutorrent')
                                    + lookup('role_var', '_docker_networks_custom', role='rutorrent') }}"

# Restart Policy
rutorrent_role_docker_restart_policy: unless-stopped

# Stop Timeout
rutorrent_role_docker_stop_timeout: 900

# State
rutorrent_role_docker_state: started
