#########################################################################
# Title:         Saltbox: UnionFS | Docker | Daemon Tasks               #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Docker | Daemon | Create override directory"
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: "0775"

- name: "Docker | Daemon | Import override file"
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: "0775"
    force: false
  register: import_override

- name: "Docker | Daemon | Edit override file"
  ini_file:
    path: /etc/systemd/system/docker.service.d/override.conf
    section: Unit
    option: "After"
    value: "{{ mount_type }}.service"
    state: present
    mode: "0755"
    no_extra_spaces: true
  register: edit_override

- name: Docker | Daemon | Restart Docker Service
  block:

    - name: "Docker | Daemon | Systemd daemon-reload"
      ansible.builtin.systemd:
        name: docker
        state: reloaded
        daemon_reload: true

    - name: "Docker | Daemon | Restart docker service"
      ansible.builtin.systemd:
        name: docker
        state: restarted

    - name: "Docker | Daemon | Wait for 30 seconds before commencing"
      ansible.builtin.wait_for:
        timeout: 30

  when: import_override.changed or edit_override.changed
