#########################################################################
# Title:         Saltbox: Backup | Sanity Check                         #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Check if 'backup.lock' is present"
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/backup.lock"
  register: backup_lock

# Age in hours
- name: "Get age of 'backup.lock' file"
  ansible.builtin.set_fact:
    backup_lock_age: "{{ ((ansible_date_time.epoch | float - backup_lock.stat.mtime) / 3600) | int }}"
  when: backup_lock.stat.exists

# Delete if older than 2 hours.
- name: "Delete stale 'backup.lock'"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/backup.lock"
    state: absent
  when: backup_lock.stat.exists and (backup_lock_age | int >= 2)

- name: "Fail when 'backup.lock' exists"
  ansible.builtin.fail:
    msg: "A Backup task is currently in progress. Please wait for it to complete."
  when: backup_lock.stat.exists and (backup_lock_age | int < 2)
