#########################################################################
# Title:         Saltbox: DNS | Defaults                                #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
cloudflare_allow_nested_proxy: false
cloudflare_reinstall: false
cloudflare_path: "/srv/cloudflare-helper"
cloudflare_venv_path: "{{ cloudflare_path }}/venv"
cloudflare_python_path: "{{ cloudflare_bin_folder }}/python3"
cloudflare_script_path: "{{ cloudflare_path }}/fetch_cloudflare_records.py"
cloudflare_requirements_path: "{{ cloudflare_path }}/requirements.txt"
cloudflare_files:
  - "fetch_cloudflare_records.py"
  - "requirements.txt"
