#########################################################################
# Title:         Saltbox: System | Logrotate Tasks                      #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# https://github.com/vbotka/ansible-linux-postinstall

- name: Logrotate | Install required packages
  apt:
    state: present
    name:
      - logrotate

- name: Logrotate | Configure '/etc/logrotate.conf'
  lineinfile:
    path: "/etc/logrotate.conf"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  loop:
    - {line: "include /etc/logrotate.d", state: "present"}

- name: Logrotate | Create 'logrotate_d_items' variable
  set_fact:
    logrotate_d_items:
      - path: "saltbox"
        content: |
          /srv/git/saltbox/saltbox.log {
              weekly
              rotate 0
              size 2M
              missingok
              notifempty
              create 644 {{ user.name }} {{ user.name }}
          }
      - path: "traefik"
        content: |
          /opt/traefik/*.log {
              rotate 5
              size 10M
              missingok
              notifempty
              postrotate
                docker kill --signal="USR1" traefik
              endscript
              create 644 {{ user.name }} {{ user.name }}
          }

- name: Logrotate | Add items to '/etc/logrotate.d'
  blockinfile:
    path: "/etc/logrotate.d/{{ item.path }}"
    marker: "### SALTBOX MANAGED BLOCK - {mark} ###"
    block: "{{ item.content }}"
    create: true
    mode: "0644"
  loop: "{{ logrotate_d_items }}"
