#########################################################################
# Title:         Saltbox: System | Mount Tasks                          #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Mounts | Display system mounts
  ansible.builtin.debug:
    msg: "{{ ansible_mounts }}"
    verbosity: 1

- name: Mounts | Set opts for '/' ext4 mount
  ansible.posix.mount:
    path: /
    opts: defaults,nodiratime,relatime
    state: present
    fstype: ext4
    src: "{{ item.device }}"
  with_items:
    - "{{ ansible_mounts }}"
  when: (item.mount == '/') and (item.fstype == 'ext4')

- name: "Mounts | Install '{{ mounts_fuse }}'"
  ansible.builtin.apt:
    name: "{{ mounts_fuse }}"
    state: present

- name: Mounts | Import 'fuse.conf'
  ansible.builtin.copy:
    src: etc/fuse.conf
    dest: /etc/fuse.conf
    mode: "0775"
    force: true
