#########################################################################
# Title:         Saltbox: System | PAM limits Tasks                     #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Set PAM limits for all users. # noqa args[module]
  community.general.pam_limits:
    domain: "*"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_type: '-', limit_item: 'nofile', value: "{{ pam_limit_nofile }}" }
    - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
    - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }

- name: Reload sysctl settings.
  ansible.builtin.shell: sysctl --system
