#########################################################################
# Title:         Saltbox: qBittorrent | Post-Install Tasks              #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Wait for config to be created
  ansible.builtin.wait_for:
    path: "{{ lookup('role_var', '_paths_conf', role='qbittorrent') }}"
    state: present

- name: Post-Install | Wait for 30 seconds
  ansible.builtin.wait_for:
    timeout: 30

- name: Post-Install | Stop container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/stop_docker_container.yml"
  when: not lookup('role_var', '_host_install', role='qbittorrent')

- name: Post-Install | Stop '{{ lookup('role_var', '_service_name', role='qbittorrent') }}'
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/systemd/manage_service.yml"
  vars:
    _service_name: "{{ lookup('role_var', '_service_name', role='qbittorrent') }}"
    _service_state: stopped
    _service_enabled: true
  when: lookup('role_var', '_host_install', role='qbittorrent')

- name: Post-Install | Settings Task
  ansible.builtin.include_tasks: "settings/main.yml"

- name: Post-Install | Start container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/start_docker_container.yml"
  when: not lookup('role_var', '_host_install', role='qbittorrent')

- name: Post-Install | Start '{{ lookup('role_var', '_service_name', role='qbittorrent') }}'
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/systemd/manage_service.yml"
  vars:
    _service_name: "{{ lookup('role_var', '_service_name', role='qbittorrent') }}"
    _service_state: started
    _service_enabled: true
  when: lookup('role_var', '_host_install', role='qbittorrent')
