##########################################################################
# Title:         Saltbox: Authelia | Default Variables                   #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

authelia_name: authelia

################################
# Configuration
################################

# Options are light, dark, grey or auto.
authelia_theme: "auto"

# Options are file or ldap
authelia_authentication_backend: "file"
authelia_authentication_backend_password_reset_disable: "false"
authelia_authentication_backend_password_reset_custom_url: ""
authelia_authentication_backend_refresh_interval: "5m"
authelia_authentication_backend_file_path: "/config/users_database.yml"
authelia_authentication_backend_file_watch: "true"
authelia_authentication_backend_file_password_algorithm: "argon2"
authelia_authentication_backend_file_password_argon2_variant: "argon2id"
authelia_authentication_backend_file_password_argon2_iterations: "3"
authelia_authentication_backend_file_password_argon2_memory: "65536"
authelia_authentication_backend_file_password_argon2_parallelism: "4"
authelia_authentication_backend_file_password_argon2_key_length: "32"
authelia_authentication_backend_file_password_argon2_salt_length: "16"

# Setting for default Access Control Policy - recommended options one_factor or two_factor
# Reference: https://www.authelia.com/configuration/security/access-control/#one_factor
authelia_access_control_policy: "one_factor"

# Settings for Duo
# Reference: https://www.authelia.com/configuration/second-factor/duo/
authelia_duo_enabled: false
authelia_duo_hostname: ""
authelia_duo_integration_key: ""
authelia_duo_secret_key: ""
authelia_duo_self_enrollment: "true"

# Settings for Webauthn
# Reference: https://www.authelia.com/configuration/second-factor/webauthn/
authelia_webauthn_disable: false
authelia_webauthn_display_name: "Authelia"
authelia_webauthn_attestation_conveyance_preference: "indirect"
authelia_webauthn_user_verification: "preferred"
authelia_webauthn_timeout: "60s"

# Settings for Notifier
# Reference: https://www.authelia.com/configuration/notifications/introduction/
# Options are filesystem or smtp. Options specific to smtp prefixed with smtp
authelia_notifier: "filesystem"
authelia_notifier_disable_startup_check: "false"
authelia_notifier_smtp_host: ""
authelia_notifier_smtp_port: ""
authelia_notifier_smtp_timeout: ""
authelia_notifier_smtp_username: ""
authelia_notifier_smtp_password: ""
authelia_notifier_smtp_sender: ""
authelia_notifier_smtp_identifier: ""
authelia_notifier_smtp_subject: ""
authelia_notifier_smtp_startup_check_address: ""
authelia_notifier_smtp_disable_require_tls: ""
authelia_notifier_smtp_disable_html_emails: ""
authelia_notifier_smtp_tls_server_name: ""
authelia_notifier_smtp_tls_skip_verify: ""
authelia_notifier_smtp_tls_minimum_version: ""

# Settings for Authelia's server
# Reference: https://www.authelia.com/configuration/miscellaneous/server/
# https://www.authelia.com/c/server#buffer-sizes
authelia_server_host: "0.0.0.0"
authelia_server_port: "9091"
authelia_server_path: ""
authelia_server_buffers_read: "10485760"
authelia_server_buffers_write: "10485760"
authelia_server_enable_pprof: "false"
authelia_server_enable_expvars: "false"
authelia_server_disable_healthcheck: "false"
authelia_server_headers_csp_template: "default-src 'self' *.{{ user.domain }} {{ user.domain }}; script-src 'self' *.{{ user.domain }} {{ user.domain }}; script-src-elem 'self' *.{{ user.domain }} {{ user.domain }}; script-src-attr 'self' *.{{ user.domain }} {{ user.domain }}; style-src 'self' *.{{ user.domain }} {{ user.domain }} 'nonce-${NONCE}'; style-src-elem 'self' *.{{ user.domain }} {{ user.domain }} 'nonce-${NONCE}'; style-src-attr 'self' *.{{ user.domain }} {{ user.domain }} 'nonce-${NONCE}'; img-src 'self' *.{{ user.domain }} {{ user.domain }}; font-src 'self' *.{{ user.domain }} {{ user.domain }}; connect-src 'self' *.{{ user.domain }} {{ user.domain }}; media-src 'self' *.{{ user.domain }} {{ user.domain }}; object-src 'self' *.{{ user.domain }} {{ user.domain }}; child-src 'self' *.{{ user.domain }} {{ user.domain }}; frame-src 'self' *.{{ user.domain }} {{ user.domain }}; worker-src 'self' *.{{ user.domain }} {{ user.domain }}; frame-ancestors 'self' *.{{ user.domain }} {{ user.domain }}; form-action 'self' *.{{ user.domain }} {{ user.domain }}; base-uri 'self'"

# Settings for Logging
# Reference: https://www.authelia.com/configuration/miscellaneous/logging/
authelia_log_level: "info"
authelia_log_format: "text"
authelia_log_file_path: "/config/authelia.log"
authelia_log_keep_stdout: "true"

# JWT
authelia_jwt_secret: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"

# TOTP
authelia_totp_issuer: "authelia.com"
authelia_totp_period: "30"
authelia_totp_skew: "1"
authelia_totp_digits: "6"
authelia_totp_secret_size: "32"

# Default redirection
authelia_default_redirection_url: ""

# Default 2FA Method
authelia_default_2fa_method: ""

# NTP
authelia_ntp_address: "time.cloudflare.com:123"
authelia_ntp_version: "3"
authelia_ntp_max_desync: "3s"
authelia_ntp_disable_startup_check: "false"
authelia_ntp_disable_failure: "false"

# Password Policy
authelia_password_policy_standard_enabled: "false"
authelia_password_policy_standard_min_length: "8"
authelia_password_policy_standard_max_length: "0"
authelia_password_policy_standard_require_uppercase: "true"
authelia_password_policy_standard_require_lowercase: "true"
authelia_password_policy_standard_require_number: "true"
authelia_password_policy_standard_require_special: "true"
authelia_password_policy_zxcvbn_enabled: "false"
authelia_password_policy_zxcvbn_min_score: "3"

# Access Control
authelia_access_control_default_policy: "deny"
authelia_access_control_rules:
  - domain:
      - "{{ '*.' + user.domain | lower }}"
      - "{{ user.domain | lower }}"
    policy: "{{ authelia_access_control_policy }}"

################################
# Paths
################################

authelia_paths_folder: "{{ authelia_name }}"
authelia_paths_location: "{{ server_appdata_path }}/{{ authelia_paths_folder }}"
authelia_paths_folders_list:
  - "{{ authelia_paths_location }}"

################################
# Web
################################

authelia_web_subdomain: "{{ authelia.subdomain }}"
authelia_web_domain: "{{ user.domain }}"
authelia_web_port: "9091"
authelia_web_url: "{{ 'https://' + (authelia_web_subdomain + '.' + authelia_web_domain
                   if (authelia_web_subdomain | length > 0)
                   else authelia_web_domain) }}"

################################
# DNS
################################

authelia_dns_record: "{{ authelia_web_subdomain }}"
authelia_dns_zone: "{{ authelia_web_domain }}"
authelia_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

authelia_traefik_sso_middleware: ""
authelia_traefik_middleware_default: "{{ traefik_default_middleware }}"
authelia_traefik_middleware_custom: ""
authelia_traefik_certresolver: "{{ traefik_default_certresolver }}"
authelia_traefik_enabled: true
authelia_traefik_api_enabled: false
authelia_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
authelia_docker_container: "{{ authelia_name }}"

# Image
authelia_docker_image_pull: true
authelia_docker_image_tag: "4.37"
authelia_docker_image: "authelia/authelia:{{ authelia_docker_image_tag }}"

# Ports
authelia_docker_ports_defaults: []
authelia_docker_ports_custom: []
authelia_docker_ports: "{{ authelia_docker_ports_defaults
                           + authelia_docker_ports_custom }}"

# Envs
authelia_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
authelia_docker_envs_custom: {}
authelia_docker_envs: "{{ authelia_docker_envs_default
                          | combine(authelia_docker_envs_custom) }}"

# Commands
authelia_docker_commands_default: []
authelia_docker_commands_custom: []
authelia_docker_commands: "{{ authelia_docker_commands_default
                              + authelia_docker_commands_custom }}"

# Volumes
authelia_docker_volumes_default:
  - "{{ authelia_paths_location }}:/config"
authelia_docker_volumes_custom: []
authelia_docker_volumes: "{{ authelia_docker_volumes_default
                             + authelia_docker_volumes_custom }}"

# Devices
authelia_docker_devices_default: []
authelia_docker_devices_custom: []
authelia_docker_devices: "{{ authelia_docker_devices_default
                             + authelia_docker_devices_custom }}"

# Hosts
authelia_docker_hosts_default: []
authelia_docker_hosts_custom: []
authelia_docker_hosts: "{{ docker_hosts_common
                           | combine(authelia_docker_hosts_default)
                           | combine(authelia_docker_hosts_custom) }}"

# Labels
authelia_docker_labels_default: {}
authelia_docker_labels_custom: {}
authelia_docker_labels: "{{ docker_labels_common
                            | combine(authelia_docker_labels_default)
                            | combine(authelia_docker_labels_custom) }}"

# Hostname
authelia_docker_hostname: "{{ authelia_name }}"

# Networks
authelia_docker_networks_alias: "{{ authelia_name }}"
authelia_docker_networks_default: []
authelia_docker_networks_custom: []
authelia_docker_networks: "{{ docker_networks_common
                              + authelia_docker_networks_default
                              + authelia_docker_networks_custom }}"

# Capabilities
authelia_docker_capabilities_default: []
authelia_docker_capabilities_custom: []
authelia_docker_capabilities: "{{ authelia_docker_capabilities_default
                                  + authelia_docker_capabilities_custom }}"

# Security Opts
authelia_docker_security_opts_default: []
authelia_docker_security_opts_custom: []
authelia_docker_security_opts: "{{ authelia_docker_security_opts_default
                                   + authelia_docker_security_opts_custom }}"

# Restart Policy
authelia_docker_restart_policy: always

# State
authelia_docker_state: started
