##########################################################################
# Title:         Saltbox: Authelia | Default Variables                   #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

authelia_name: authelia

################################
# Settings
################################

# Options are light, dark, grey or auto.
authelia_role_theme: "auto"

# Logs
authelia_role_log_max_backups: "3"
authelia_role_log_max_size: "10"

# Options are file or ldap
authelia_role_authentication_backend: "file"
authelia_role_authentication_backend_password_reset_disable: "false"
authelia_role_authentication_backend_password_reset_custom_url: ""
authelia_role_authentication_backend_refresh_interval: "5m"
authelia_role_authentication_backend_file_path: "/config/users_database.yml"
authelia_role_authentication_backend_file_watch: "true"
authelia_role_authentication_backend_file_password_algorithm: "argon2"
authelia_role_authentication_backend_file_password_argon2_variant: "argon2id"
authelia_role_authentication_backend_file_password_argon2_iterations: "3"
authelia_role_authentication_backend_file_password_argon2_memory: "65536"
authelia_role_authentication_backend_file_password_argon2_parallelism: "4"
authelia_role_authentication_backend_file_password_argon2_key_length: "32"
authelia_role_authentication_backend_file_password_argon2_salt_length: "16"

# Setting for default Access Control Policy - recommended options one_factor or two_factor
# Reference: https://www.authelia.com/configuration/security/access-control/#one_factor
authelia_role_access_control_policy: "one_factor"

# Settings for Duo
# Reference: https://www.authelia.com/configuration/second-factor/duo/
authelia_role_duo_enabled: false
authelia_role_duo_hostname: ""
authelia_role_duo_integration_key: ""
authelia_role_duo_secret_key: ""
authelia_role_duo_self_enrollment: "true"

# Settings for Webauthn
# Reference: https://www.authelia.com/configuration/second-factor/webauthn/
authelia_role_webauthn_disable: false
authelia_role_webauthn_display_name: "Authelia"
authelia_role_webauthn_attestation_conveyance_preference: "indirect"
authelia_role_webauthn_user_verification: "preferred"
authelia_role_webauthn_timeout: "60s"

# Settings for Notifier
# Reference: https://www.authelia.com/configuration/notifications/introduction/
# Options are filesystem or smtp. Options specific to smtp prefixed with smtp
authelia_role_notifier: "filesystem"
authelia_role_notifier_disable_startup_check: "false"
authelia_role_notifier_smtp_host: ""
authelia_role_notifier_smtp_port: ""
authelia_role_notifier_smtp_timeout: ""
authelia_role_notifier_smtp_username: ""
authelia_role_notifier_smtp_password: ""
authelia_role_notifier_smtp_sender: ""
authelia_role_notifier_smtp_identifier: ""
authelia_role_notifier_smtp_subject: ""
authelia_role_notifier_smtp_startup_check_address: ""
authelia_role_notifier_smtp_disable_require_tls: ""
authelia_role_notifier_smtp_disable_html_emails: ""
authelia_role_notifier_smtp_tls_server_name: ""
authelia_role_notifier_smtp_tls_skip_verify: ""
authelia_role_notifier_smtp_tls_minimum_version: ""

# Settings for Authelia's server
# Reference: https://www.authelia.com/configuration/miscellaneous/server/
# https://www.authelia.com/c/server#buffer-sizes
authelia_role_server_address: "0.0.0.0:9091"
authelia_role_server_buffers_read: "10485760"
authelia_role_server_buffers_write: "10485760"
authelia_role_server_enable_pprof: "false"
authelia_role_server_enable_expvars: "false"
authelia_role_server_disable_healthcheck: "false"
authelia_role_server_headers_csp_template: "default-src 'self' *.{{ user.domain }} {{ user.domain }}; script-src 'self' *.{{ user.domain }} {{ user.domain }}; script-src-elem 'self' *.{{ user.domain }} {{ user.domain }}; script-src-attr 'self' *.{{ user.domain }} {{ user.domain }}; style-src 'self' *.{{ user.domain }} {{ user.domain }} 'nonce-${NONCE}'; style-src-elem 'self' *.{{ user.domain }} {{ user.domain }} 'nonce-${NONCE}'; style-src-attr 'self' *.{{ user.domain }} {{ user.domain }} 'nonce-${NONCE}'; img-src 'self' *.{{ user.domain }} {{ user.domain }}; font-src 'self' *.{{ user.domain }} {{ user.domain }}; connect-src 'self' *.{{ user.domain }} {{ user.domain }}; media-src 'self' *.{{ user.domain }} {{ user.domain }}; object-src 'self' *.{{ user.domain }} {{ user.domain }}; child-src 'self' *.{{ user.domain }} {{ user.domain }}; frame-src 'self' *.{{ user.domain }} {{ user.domain }}; worker-src 'self' *.{{ user.domain }} {{ user.domain }}; frame-ancestors 'self' *.{{ user.domain }} {{ user.domain }}; form-action 'self' *.{{ user.domain }} {{ user.domain }}; base-uri 'self'"

# Settings for Logging
# Reference: https://www.authelia.com/configuration/miscellaneous/logging/
authelia_role_log_level: "info"
authelia_role_log_format: "text"
authelia_role_log_file_path: "/config/authelia.log"
authelia_role_log_keep_stdout: "true"

# JWT
authelia_role_jwt_secret: "{{ lookup('password', '/dev/null', chars=['ascii_letters', 'digits'], length=32) }}"

# TOTP
authelia_role_totp_issuer: "{{ lookup('role_var', '_web_subdomain', role='authelia') + '.' + lookup('role_var', '_web_domain', role='authelia') }}"
authelia_role_totp_period: "30"
authelia_role_totp_skew: "1"
authelia_role_totp_digits: "6"
authelia_role_totp_secret_size: "32"

# Default redirection
authelia_role_default_redirection_url: ""

# Default 2FA Method
authelia_role_default_2fa_method: ""

# NTP
authelia_role_ntp_address: "time.cloudflare.com:123"
authelia_role_ntp_version: "3"
authelia_role_ntp_max_desync: "3s"
authelia_role_ntp_disable_startup_check: "false"
authelia_role_ntp_disable_failure: "false"

# Password Policy
authelia_role_password_policy_standard_enabled: "false"
authelia_role_password_policy_standard_min_length: "8"
authelia_role_password_policy_standard_max_length: "0"
authelia_role_password_policy_standard_require_uppercase: "true"
authelia_role_password_policy_standard_require_lowercase: "true"
authelia_role_password_policy_standard_require_number: "true"
authelia_role_password_policy_standard_require_special: "true"
authelia_role_password_policy_zxcvbn_enabled: "false"
authelia_role_password_policy_zxcvbn_min_score: "3"

# Access Control
authelia_role_access_control_whitelist_host: false
authelia_role_access_control_default_policy: "deny"
authelia_role_access_control_rules:
  - domain:
      - "{{ '*.' + user.domain | lower }}"
      - "{{ user.domain | lower }}"
    policy: "{{ lookup('role_var', '_access_control_policy', role='authelia') }}"

authelia_role_access_control_whitelist_rules_lookup: "{{ lookup('role_var', '_access_control_whitelist_rules', role='authelia') if lookup('role_var', '_access_control_whitelist_host', role='authelia') and ((dns.ipv4 | default(true)) or (dns.ipv6 | default(false))) else [] }}"

authelia_role_access_control_whitelist_rules:
  - domain:
      - "{{ '*.' + user.domain }}"
      - "{{ user.domain }}"
    policy: bypass
    networks: "{{ lookup('role_var', '_access_control_whitelist_networks', role='authelia') | unique | reject('equalto', omit) | list }}"

authelia_role_access_control_whitelist_networks:
  - "{{ (ip_address_public + '/32') if (dns.ipv4 | default(true)) else omit }}"
  - "{{ (ipv6_address_public + '/128') if (dns.ipv6 | default(false)) else omit }}"

authelia_role_response_headers:
  - "Remote-User"
  - "Remote-Groups"
  - "Remote-Name"
  - "Remote-Email"

################################
# Paths
################################

authelia_role_paths_folder: "{{ authelia_name }}"
authelia_role_paths_location: "{{ server_appdata_path }}/{{ authelia_role_paths_folder }}"
authelia_role_paths_folders_list:
  - "{{ authelia_role_paths_location }}"

################################
# Web
################################

authelia_role_web_subdomain: "{{ authelia.subdomain }}"
authelia_role_web_domain: "{{ user.domain }}"
authelia_role_web_port: "9091"
authelia_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='authelia') + '.' + lookup('role_var', '_web_domain', role='authelia')
                        if (lookup('role_var', '_web_subdomain', role='authelia') | length > 0)
                        else lookup('role_var', '_web_domain', role='authelia')) }}"

################################
# DNS
################################

authelia_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='authelia') }}"
authelia_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='authelia') }}"
authelia_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

authelia_role_traefik_sso_middleware: ""
authelia_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
authelia_role_traefik_middleware_custom: ""
authelia_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
authelia_role_traefik_enabled: true
authelia_role_traefik_api_enabled: false
authelia_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
authelia_role_docker_container: "{{ authelia_name }}"

# Image
authelia_role_docker_image_pull: true
authelia_role_docker_image_repo: "authelia/authelia"
authelia_role_docker_image_tag: "4.39"
authelia_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='authelia') }}:{{ lookup('role_var', '_docker_image_tag', role='authelia') }}"

# Envs
authelia_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
authelia_role_docker_envs_custom: {}
authelia_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='authelia')
                               | combine(lookup('role_var', '_docker_envs_custom', role='authelia')) }}"

# Volumes
authelia_role_docker_volumes_default:
  - "{{ authelia_role_paths_location }}:/config"
authelia_role_docker_volumes_custom: []
authelia_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='authelia')
                                  + lookup('role_var', '_docker_volumes_custom', role='authelia') }}"

# Hostname
authelia_role_docker_hostname: "{{ authelia_name }}"

# Networks
authelia_role_docker_networks_alias: "{{ authelia_name }}"
authelia_role_docker_networks_default: []
authelia_role_docker_networks_custom: []
authelia_role_docker_networks: "{{ docker_networks_common
                                   + lookup('role_var', '_docker_networks_default', role='authelia')
                                   + lookup('role_var', '_docker_networks_custom', role='authelia') }}"

# Restart Policy
authelia_role_docker_restart_policy: unless-stopped

# State
authelia_role_docker_state: started

# Dependencies
authelia_role_depends_on: "{{ 'authelia-redis,lldap' if (lookup('role_var', '_authentication_backend', role='authelia') == 'ldap') else 'authelia-redis' }}"
authelia_role_depends_on_delay: "0"
authelia_role_depends_on_healthchecks: "{{ 'true' if (lookup('role_var', '_authentication_backend', role='authelia') == 'ldap') else 'false' }}"
