#########################################################################
# Title:         Saltbox: Docker | Docker Hub Tasks                     #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Docker Hub | Login
  community.docker.docker_login:
    username: "{{ dockerhub.user }}"
    password: "{{ dockerhub.token }}"

- name: Docker Hub | Login
  community.docker.docker_login:
    username: "{{ dockerhub.user }}"
    password: "{{ dockerhub.token }}"
  become: true
  become_user: "{{ user.name }}"
