#########################################################################
# Title:         Saltbox: Docker | Binary Tasks 2                       #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Binary | Release '{{ lookup('vars', item ~ '_dpkg') }}' from hold
  ansible.builtin.dpkg_selections:
    name: "{{ lookup('vars', item ~ '_dpkg') }}"
    selection: install
  when: (lookup('vars', item ~ '_dpkg') in ansible_facts['packages'])

- name: Binary | Install '{{ lookup('vars', item + '_package') }}'
  ansible.builtin.apt:
    name: "{{ lookup('vars', item + '_package') }}"
    state: "{{ 'present' if (item == 'docker_ce' or item == 'docker_ce_cli') else 'latest' }}"
    update_cache: true
    allow_downgrade: true

- name: Binary | Put '{{ lookup('vars', item ~ '_dpkg') }}' into hold
  ansible.builtin.dpkg_selections:
    name: "{{ lookup('vars', item ~ '_dpkg') }}"
    selection: hold
  when: put_docker_dpkg_into_hold

- name: Binary | Get '{{ lookup('vars', item ~ '_name') }}' version
  ansible.builtin.shell: "{{ lookup('vars', item ~ '_filepath') }} '{{ 'version' if item == 'compose_cli' else '--version' }}' | head -n 1 | awk '{ print {{ '$4' if item == 'compose_cli' else '$3' }} }' | sed 's/,$//' | sed 's/v//'"
  register: binary_version
  ignore_errors: true
  changed_when: false

- name: Binary | Display '{{ lookup('vars', item ~ '_name') }}' version
  ansible.builtin.debug:
    msg: "{{ lookup('vars', item ~ '_name') }} version {{ binary_version.stdout }} installed."
  when: binary_version is defined
