#########################################################################
# Title:         Saltbox: Nethogs Role                                  #
# Author(s):     EnorMOZ, desimaniac                                    #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Make sure NetHogs package is not installed
  ansible.builtin.apt:
    name: nethogs
    state: absent

- name: Install NetHogs dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - libncurses5-dev
      - libpcap-dev
    state: present
    update_cache: true

- name: Pull NetHogs repo from github
  ansible.builtin.git:
    repo: "{{ nethogs_git_repo_url }}"
    dest: "{{ nethogs_git_repo_dest }}"
    clone: true
    version: HEAD
    force: true
  register: nethogs_clone_status

- name: Tasks to do with git clone is a success
  block:

    - name: Build and install NetHogs
      ansible.builtin.shell: "{{ nethogs_binary_build_command }}"

    - name: Get NetHogs binary version
      ansible.builtin.shell: "{{ nethogs_binary_version_lookup_command }}"
      register: nethogs_binary_version

    - name: Display nethogs binary version
      ansible.builtin.debug:
        msg: "NetHogs {{ nethogs_binary_version.stdout }} installed."

  when: (nethogs_clone_status is succeeded)
