#########################################################################
# Title:         Saltbox: qBittorrent Role                              #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute qBittorrent roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    qbittorrent_name: "{{ role }}"
  with_items: "{{ qbittorrent_instances }}"
  loop_control:
    loop_var: role
