#########################################################################
# Title:         Saltbox: DNS | Cloudflare | Remove DNS Record          #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Cloudflare | Remove DNS Record | IPv4 | Remove DNS Record
  community.general.cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    zone: "{{ dns_zone }}"
    state: absent
    type: A
    record: "{{ dns_record }}"
  register: cloudflare_dns_record_removal_status

- name: Cloudflare | Remove DNS Record | IPv4 | Tasks on success
  block:

    - name: Cloudflare | Remove DNS Record | IPv4 | Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        dns_record_print: "{{ (dns_record == dns_zone) | ternary(dns_zone, dns_record + '.' + dns_zone) }}"

    - name: Cloudflare | Remove DNS Record | IPv4 | Display DNS Record removal status
      ansible.builtin.debug:
        msg: "DNS A Record for '{{ dns_record_print }}' was removed."

  when: cloudflare_dns_record_removal_status is succeeded


- name: Cloudflare | Remove DNS Record | IPv6 | Remove DNS Record
  community.general.cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    zone: "{{ dns_zone }}"
    state: absent
    type: AAAA
    record: "{{ dns_record }}"
  register: cloudflare_dns_v6_record_removal_status

- name: Cloudflare | Remove DNS Record | IPv6 | Tasks on success
  block:

    - name: Cloudflare | Remove DNS Record | IPv6 | Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        dns_record_print: "{{ (dns_record == dns_zone) | ternary(dns_zone, dns_record + '.' + dns_zone) }}"

    - name: Cloudflare | Remove DNS Record | IPv6 | Display DNS Record removal status
      ansible.builtin.debug:
        msg: "DNS AAAA Record for '{{ dns_record_print }}' was removed."

  when: cloudflare_dns_v6_record_removal_status is succeeded
