#########################################################################
# Title:         Saltbox: DNS | Cloudflare | Validate Task              #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Cloudflare | Validate | Validate Cloudflare Credentials
  ansible.builtin.shell: |
    curl -X GET "https://api.cloudflare.com/client/v4/user" \
    -H "X-Auth-Email: {{ cloudflare.email }}" \
    -H "X-Auth-Key: {{ cloudflare.api }}" \
    -H "Content-Type: application/json"
  register: cloudflare_validation
  ignore_errors: true

- name: Cloudflare | Validate | Print if successful
  ansible.builtin.debug:
    msg: "Cloudflare Credentials Validated"
  when: (cloudflare_validation.stdout | from_json).success

- name: Cloudflare | Validate | Fail if unsuccessful
  ansible.builtin.fail:
    msg: "Cloudflare Credentials Incorrect"
  when: (not (cloudflare_validation.stdout | from_json).success)
