##########################################################################
# Title:         Saltbox: Autobrr | Default Variables                    #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

autobrr_name: autobrr

################################
# Paths
################################

autobrr_role_paths_folder: "{{ autobrr_name }}"
autobrr_role_paths_location: "{{ server_appdata_path }}/{{ autobrr_role_paths_folder }}"
autobrr_role_paths_config_location: "{{ autobrr_role_paths_location }}/config.toml"
autobrr_role_paths_folders_list:
  - "{{ autobrr_role_paths_location }}"

################################
# Web
################################

autobrr_role_web_subdomain: "{{ autobrr_name }}"
autobrr_role_web_domain: "{{ user.domain }}"
autobrr_role_web_port: "7474"
autobrr_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='autobrr') + '.' + lookup('role_var', '_web_domain', role='autobrr')
                       if (lookup('role_var', '_web_subdomain', role='autobrr') | length > 0)
                       else lookup('role_var', '_web_domain', role='autobrr')) }}"

################################
# DNS
################################

autobrr_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='autobrr') }}"
autobrr_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='autobrr') }}"
autobrr_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

autobrr_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
autobrr_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
autobrr_role_traefik_middleware_custom: ""
autobrr_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
autobrr_role_traefik_enabled: true
autobrr_role_traefik_api_enabled: true
autobrr_role_traefik_api_endpoint: "PathPrefix(`/api`)"

################################
# Docker
################################

# Container
autobrr_role_docker_container: "{{ autobrr_name }}"

# Image
autobrr_role_docker_image_pull: true
autobrr_role_docker_image_repo: "ghcr.io/autobrr/autobrr"
autobrr_role_docker_image_tag: "latest"
autobrr_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='autobrr') }}:{{ lookup('role_var', '_docker_image_tag', role='autobrr') }}"

# Envs
autobrr_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
autobrr_role_docker_envs_custom: {}
autobrr_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='autobrr')
                              | combine(lookup('role_var', '_docker_envs_custom', role='autobrr')) }}"

# Volumes
autobrr_role_docker_volumes_default:
  - "{{ autobrr_role_paths_location }}:/config"
autobrr_role_docker_volumes_custom: []
autobrr_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='autobrr')
                                 + lookup('role_var', '_docker_volumes_custom', role='autobrr') }}"

# Hostname
autobrr_role_docker_hostname: "{{ autobrr_name }}"

# Networks
autobrr_role_docker_networks_alias: "{{ autobrr_name }}"
autobrr_role_docker_networks_default: []
autobrr_role_docker_networks_custom: []
autobrr_role_docker_networks: "{{ docker_networks_common
                                  + lookup('role_var', '_docker_networks_default', role='autobrr')
                                  + lookup('role_var', '_docker_networks_custom', role='autobrr') }}"

# Restart Policy
autobrr_role_docker_restart_policy: unless-stopped

# State
autobrr_role_docker_state: started
