#########################################################################
# Title:         Saltbox: NZBGet | Post-Install Tasks                   #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Wait for config file to be created
  ansible.builtin.wait_for:
    path: "{{ nzbget_paths_config_location }}"
    state: present

- name: Post-Install | Wait for 10 seconds
  ansible.builtin.wait_for:
    timeout: 10

- name: Post-Install | Stop container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/stop_docker_container.yml"
  vars:
    var_prefix: "{{ nzbget_docker_container }}"

- name: Post-Install | Scripts Task
  ansible.builtin.import_tasks: "scripts/main.yml"

- name: Post-Install | Settings Task
  ansible.builtin.import_tasks: "settings/main.yml"

- name: Post-Install | Start container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/start_docker_container.yml"
  vars:
    var_prefix: "{{ nzbget_docker_container }}"
