#########################################################################
# Title:         Saltbox: Remote | Container Tasks                      #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Containers | Gather list of running Docker containers"
  ansible.builtin.shell: "docker ps --format '{{ '{{' }} .Names{{ '}}' }}' --filter label=com.github.saltbox.saltbox_managed=true | xargs echo -n"
  register: saltbox_managed_containers
  ignore_errors: true

# This is needed to not conflict with the other role
- name: "Containers | Set 'containers_list' variable"
  ansible.builtin.set_fact:
    containers_list: "{{ saltbox_managed_containers.stdout }}"

- name: "Containers | Stop all running Docker containers"
  ansible.builtin.shell: "docker stop {{ containers_list }}"
  ignore_errors: true
  when: (containers_list | trim | length > 0)
