##########################################################################
# Title:         Saltbox: Remote | Variable Tasks                        #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Mount Types
################################

- name: Variables | Set 'rclone_vfs' mount variables
  ansible.builtin.set_fact:
    desired_mount_types: ['rclone_vfs']
  when: (mounts.remote | lower == 'rclone_vfs')

- name: Variables | Set 'rclone_vfs_cache' mount variables
  ansible.builtin.set_fact:
    desired_mount_types: ['rclone_vfs_cache']
  when: (mounts.remote | lower == 'rclone_vfs_cache')

- name: Variables | Set 'mount_types_is_defined' variable
  ansible.builtin.set_fact:
    mount_types_is_defined: "{{ (desired_mount_types is defined) and
                                (desired_mount_types is not none) and
                                (desired_mount_types | trim | length > 0) }}"

- name: Variables | Fail when no valid remote mount type is specified.
  ansible.builtin.fail:
    msg: "'{{ mounts.remote }}' is not a valid remote mount type."
  when: (not mount_types_is_defined) and (not feeder_mount_is_enabled)

################################
# Feeder
################################

- name: Variables | Add feeder entries to variable
  block:

    - name: Variables | Add 'feeder' to 'mount_types' variable
      ansible.builtin.set_fact:
        desired_mount_types: "{{ desired_mount_types + ['feeder'] }}"

  when: feeder_mount_is_enabled

################################
# Mount Paths
################################

- name: Variables | Set 'mount_paths' variable
  ansible.builtin.set_fact:
    mount_paths:
      - '/mnt/remote'
      - '/mnt/feeder'

################################
# Service Files
################################

- name: Variables | Set 'service_files' variable
  ansible.builtin.set_fact:
    service_files:
      - 'rclone_vfs.service'
      - 'feeder.service'

- name: Variables | Set 'service_files_stat' variable
  ansible.builtin.stat:
    path: "/etc/systemd/system/{{ item }}"
  register: service_files_stat
  loop: "{{ service_files }}"

- name: Variables | Create empty 'service_files_temp' variable
  ansible.builtin.set_fact:
    service_files_temp: []

- name: Variables | Build 'service_files_temp' variable
  ansible.builtin.set_fact:
    service_files_temp: "{{ service_files_temp + [item.item] }}"
  when: item.stat.exists
  loop: "{{ service_files_stat.results }}"

- name: Variables | Set new 'service_files' variable
  ansible.builtin.set_fact:
    service_files: "{{ service_files_temp }}"
