#########################################################################
# Title:         Saltbox: Hetzner | Restart Tasks                       #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Restart only after changes

- name: "Restart | Set preinstall variables"
  ansible.builtin.set_fact:
    preinstall_kernel_restart: true
  when: ('preinstall' in ansible_run_tags)

- name: Restart | Tasks for non-preinstall
  when: ('hetzner' in ansible_run_tags)
  block:
    - name: Restart | Success message
      ansible.builtin.debug:
        msg:
          - "GRUB was updated."
          - "Restarting the server to apply changes..."

    - name: Restart | Reboot
      ansible.builtin.shell: reboot

    - name: Restart | Reboot message
      ansible.builtin.debug:
        msg:
          - "Failed to reboot automatically."
          - "You will need to restart the server yourself for changes to take effect."
