#########################################################################
# Title:         Saltbox: Plex Dupefinder Role                          #
# Author(s):     l3uddz                                                 #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create plex_dupefinder directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    recurse: yes
  with_items:
    - /opt/plex_dupefinder

- name: Clone plex_dupefinder
  git:
    repo: https://github.com/saltyorg/plex_dupefinder.git
    dest: /opt/plex_dupefinder
    clone: true
    version: HEAD
    force: true
  become: true
  become_user: "{{ user.name }}"

- name: Install pip requirements
  pip:
    requirements: /opt/plex_dupefinder/requirements.txt
    executable: pip3
    virtualenv_python: python3
    virtualenv: "/opt/plex_dupefinder/venv"
  become: true
  become_user: "{{ user.name }}"

- name: Check config exists
  stat:
    path: "/opt/plex_dupefinder/config.json"
  register: plex_dupefinder_config

- name: Import Plex Auth Token role
  import_role:
    name: plex_auth_token
  when: plex_account_is_enabled and not plex_dupefinder_config.stat.exists

- name: Import default config
  template:
    src: config.json.j2
    dest: /opt/plex_dupefinder/config.json
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    force: false
  when: not plex_dupefinder_config.stat.exists

- name: Set plexdupes.py as executable
  file:
    path: /opt/plex_dupefinder/plex_dupefinder.py
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: a+x

- name: "Create /usr/local/bin symlink"
  file:
    src: "/opt/plex_dupefinder/plex_dupefinder.py"
    dest: "/usr/local/bin/plex_dupefinder"
    state: link
