##########################################################################
# Title:         Saltbox: Plex | Modify Binary Tasks                     #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Modify Binary | Import 'bbe'
  ansible.builtin.copy:
    src: bbe
    force: true
    dest: "{{ server_appdata_path }}/scripts/bbe"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

- name: Modify Binary | Import '99-modify-binary'
  ansible.builtin.copy:
    src: 99-modify-binary
    force: true
    dest: "{{ plex_paths_location }}/99-modify-binary"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
