##########################################################################
# Title:         Saltbox: MongoDB | Default Variables                    #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

mongodb_name: mongo

################################
# Paths
################################

mongodb_paths_folder: "{{ mongodb_name }}"
mongodb_paths_location: "{{ server_appdata_path }}/{{ mongodb_paths_folder }}"
mongodb_paths_folders_list:
  - "{{ mongodb_paths_location }}"
  - "{{ mongodb_paths_location }}/config"

################################
# Docker
################################

# Container
mongodb_docker_container: "{{ mongodb_name }}"

# Image
mongodb_docker_image_pull: true
mongodb_docker_image_tag: "latest"
mongodb_docker_image: "mongo:{{ mongodb_docker_image_tag }}"

# Ports
mongodb_docker_ports_defaults: []
mongodb_docker_ports_custom: []
mongodb_docker_ports: "{{ mongodb_docker_ports_defaults
                          + mongodb_docker_ports_custom }}"

# Envs
mongodb_docker_envs_default:
  MONGO_DATA_DIR: "/data/db"
  MONGO_LOG_DIR: "/dev/null"
  MONGO_URL: "mongodb://mongo:27017/"
mongodb_docker_envs_custom: {}
mongodb_docker_envs: "{{ mongodb_docker_envs_default
                         | combine(mongodb_docker_envs_custom) }}"

# Commands
mongodb_docker_commands_default: []
mongodb_docker_commands_custom: []
mongodb_docker_commands: "{{ mongodb_docker_commands_default
                             + mongodb_docker_commands_custom }}"

# Volumes
mongodb_docker_volumes_default:
  - "{{ mongodb_paths_location }}:/data/db:rw"
  - "{{ mongodb_paths_location }}/config:/data/configdb"
mongodb_docker_volumes_custom: []
mongodb_docker_volumes: "{{ mongodb_docker_volumes_default
                            + mongodb_docker_volumes_custom }}"

# Devices
mongodb_docker_devices_default: []
mongodb_docker_devices_custom: []
mongodb_docker_devices: "{{ mongodb_docker_devices_default
                            + mongodb_docker_devices_custom }}"

# Hosts
mongodb_docker_hosts_default: []
mongodb_docker_hosts_custom: []
mongodb_docker_hosts: "{{ docker_hosts_common
                          | combine(mongodb_docker_hosts_default)
                          | combine(mongodb_docker_hosts_custom) }}"

# Labels
mongodb_docker_labels_default: {}
mongodb_docker_labels_custom: {}
mongodb_docker_labels: "{{ docker_labels_common
                           | combine(mongodb_docker_labels_default)
                           | combine(mongodb_docker_labels_custom) }}"

# Hostname
mongodb_docker_hostname: "{{ mongodb_name }}"

# Networks
mongodb_docker_networks_alias: "{{ mongodb_name }}"
mongodb_docker_networks_default: []
mongodb_docker_networks_custom: []
mongodb_docker_networks: "{{ docker_networks_common
                             + mongodb_docker_networks_default
                             + mongodb_docker_networks_custom }}"

# Capabilities
mongodb_docker_capabilities_default: []
mongodb_docker_capabilities_custom: []
mongodb_docker_capabilities: "{{ mongodb_docker_capabilities_default
                                 + mongodb_docker_capabilities_custom }}"

# Security Opts
mongodb_docker_security_opts_default: []
mongodb_docker_security_opts_custom: []
mongodb_docker_security_opts: "{{ mongodb_docker_security_opts_default
                                  + mongodb_docker_security_opts_custom }}"

# Restart Policy
mongodb_docker_restart_policy: unless-stopped

# State
mongodb_docker_state: started

# User
mongodb_docker_user: "{{ uid }}:{{ gid }}"
