#########################################################################
# Title:         Saltbox: iperf3 Role                                   #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Make sure iperf3 package is not installed
  ansible.builtin.apt:
    name: iperf3
    state: absent

- name: Clone iperf3 repo
  ansible.builtin.git:
    repo: "{{ iperf3_git_repo_url }}"
    dest: "{{ iperf3_git_repo_dest }}"
    clone: true
    version: HEAD
    force: true
  register: iperf_clone_status

- name: Tasks to do with git clone is a success
  block:

    - name: Build and install iperf3
      ansible.builtin.shell: "{{ iperf3_binary_build_command }}"

    - name: Get iperf3 binary version
      ansible.builtin.shell: "{{ iperf3_binary_version_lookup_command }}"
      register: iperf3_binary_version

    - name: Display iperf3 binary version
      ansible.builtin.debug:
        msg: "iperf3 {{ iperf3_binary_version.stdout }} installed."

  when: (iperf_clone_status is success)
