##########################################################################
# Title:         Saltbox: Seerr | Default Variables                      #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

seerr_instances: ["seerr"]

################################
# Settings
################################

seerr_role_log_level: "info"

################################
# Paths
################################

seerr_role_paths_folder: "{{ seerr_name }}"
seerr_role_paths_location: "{{ server_appdata_path }}/{{ seerr_role_paths_folder }}"
seerr_role_paths_cache: "{{ seerr_role_paths_location }}/cache"
seerr_role_paths_folders_list:
  - "{{ seerr_role_paths_location }}"
  - "{{ seerr_role_paths_cache }}"
seerr_role_paths_config_location: "{{ seerr_role_paths_location }}/settings.json"

################################
# Web
################################

seerr_role_web_subdomain: "{{ seerr_name }}"
seerr_role_web_domain: "{{ user.domain }}"
seerr_role_web_port: "5055"
seerr_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='seerr') + '.' + lookup('role_var', '_web_domain', role='seerr')
                         if (lookup('role_var', '_web_subdomain', role='seerr') | length > 0)
                         else lookup('role_var', '_web_domain', role='seerr')) }}"

################################
# DNS
################################

seerr_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='seerr') }}"
seerr_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='seerr') }}"
seerr_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

seerr_role_traefik_sso_middleware: ""
seerr_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
seerr_role_traefik_middleware_custom: ""
seerr_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
seerr_role_traefik_enabled: true
seerr_role_traefik_api_enabled: false
seerr_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
seerr_role_docker_container: "{{ seerr_name }}"

# Image
seerr_role_docker_image_pull: true
seerr_role_docker_image_repo: "ghcr.io/hotio/seerr"
seerr_role_docker_image_tag: "latest"
seerr_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='seerr') }}:{{ lookup('role_var', '_docker_image_tag', role='seerr') }}"

# Envs
seerr_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  UMASK: "002"
  TZ: "{{ tz }}"
  LOG_LEVEL: "{{ lookup('role_var', '_log_level', role='seerr') }}"
seerr_role_docker_envs_custom: {}
seerr_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='seerr')
                            | combine(lookup('role_var', '_docker_envs_custom', role='seerr')) }}"

# Volumes
seerr_role_docker_volumes_default:
  - "{{ seerr_role_paths_location }}:/config"
seerr_role_docker_volumes_custom: []
seerr_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='seerr')
                               + lookup('role_var', '_docker_volumes_custom', role='seerr') }}"

# Labels
seerr_role_docker_labels_default: {}
seerr_role_docker_labels_custom: {}
seerr_role_docker_labels: "{{ lookup('role_var', '_docker_labels_default', role='seerr')
                              | combine(lookup('role_var', '_docker_labels_custom', role='seerr')) }}"

# Hostname
seerr_role_docker_hostname: "{{ seerr_name }}"

# Networks
seerr_role_docker_networks_alias: "{{ seerr_name }}"
seerr_role_docker_networks_default: []
seerr_role_docker_networks_custom: []
seerr_role_docker_networks: "{{ docker_networks_common
                                + lookup('role_var', '_docker_networks_default', role='seerr')
                                + lookup('role_var', '_docker_networks_custom', role='seerr') }}"

# Restart Policy
seerr_role_docker_restart_policy: unless-stopped

# State
seerr_role_docker_state: started
