########################################################################################
# Title:         Saltbox: Settings | Migrator | 'backup_config.yml' | Migration 01     #
# Author(s):     desimaniac, salty                                                     #
# URL:           https://github.com/saltyorg/Saltbox                                   #
# --                                                                                   #
########################################################################################
#                            GNU General Public License v3.0                           #
########################################################################################

---
- name: "Migrator | 'backup_config.yml' | Migration 01 | Set variables"
  ansible.builtin.set_fact:
    new_settings: "{{ true if not
        ((backup is undefined)
        or
        (backup is none)
        or
        (backup | trim | length == 0)
        or
        (backup.cron is undefined)
        or
        (backup.cron is none)
        or
        (backup.cron | trim | length == 0)
        or
        (backup.cron.cron_state is defined))
        else false }}"

- name: Migrator | 'backup_config.yml' | Migration 01 | Rebuild 'backup.cron' dict
  ansible.builtin.shell: |
    yyq e -i 'del(.backup.cron.cron_state)' {{ playbook_dir }}/{{ file }}
    yyq e -i '.backup.cron.enable = "{{
              'yes'
              if (backup is defined and backup.cron is defined and backup.cron.cron_state is defined and backup.cron.cron_state == "present")
              else 'no' }}"' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: (not new_settings)

- name: Migrator | 'backup_config.yml' | Migration 01 | Remove 'null' values
  ansible.builtin.replace:
    path: "{{ playbook_dir }}/{{ file }}"
    regexp: '(?<=: )\bnull\s*$'
    replace: ''
    owner: "{{ saltbox_yml.stat.uid }}"
    group: "{{ saltbox_yml.stat.gid }}"
    mode: "0664"

- name: Migrator | 'backup_config.yml' | Migration 01 | Re-import Variables
  ansible.builtin.include_vars: "{{ playbook_dir }}/{{ file }}"
