#########################################################################
# Title:         Saltbox: Common Role | BTRFS Task                      #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: BTRFS | Check if '{{ outer_item }}' exists
  ansible.builtin.stat:
    path: "{{ outer_item }}"
  register: outer_item_stat

- name: BTRFS | Do following tasks when '{{ outer_item }}' does not exist
  when: (not outer_item_stat.stat.exists)
  block:
    - name: BTRFS | Create '{{ outer_item }}' path
      ansible.builtin.file:
        path: "{{ outer_item }}"
        state: directory
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0775"

    - name: BTRFS | Check file system on '{{ outer_item }}'
      ansible.builtin.shell: stat -f -c %T "{{ outer_item }}"
      register: outer_item_file_system

    - name: BTRFS | Set NOCOW on '{{ outer_item }} if BTRFS'
      ansible.builtin.shell: "chattr +C {{ outer_item }}"
      when: ('btrfs' in outer_item_file_system.stdout)
