##########################################################################
# Title:         Saltbox: Notify | Default Variables                     #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Accounts
################################

apprise_account_is_enabled: "{{ (apprise is defined) and
                                (apprise is not none) and
                                (apprise | trim | length > 0) }}"
