#########################################################################
# Title:         Saltbox: Traefik | Cloudflare Task                     #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Get IPs from Cloudflare
  ansible.builtin.uri:
    url: https://api.cloudflare.com/client/v4/ips
    method: GET
    return_content: true
  register: cloudflare_ips
  retries: "5"
  delay: 10
  until: cloudflare_ips.status == 200

- name: Create Cloudflare IPv4 and IPv6 variables
  ansible.builtin.set_fact:
    traefik_cloudflare_ipv4: "{{ cloudflare_ips.json.result.ipv4_cidrs }}"
    traefik_cloudflare_ipv6: "{{ cloudflare_ips.json.result.ipv6_cidrs }}"
  when: (cloudflare_ips.status == 200) and cloudflare_ips.json.success

- name: "Fail when unable to get API output"
  ansible.builtin.fail:
    msg: Failed to retrieve API output.
  when: (cloudflare_ips.status != 200) or (not cloudflare_ips.json.success)
