#########################################################################
# Title:         Saltbox: Traefik Role                                  #
# Author(s):     RXWatcher, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('role_var', '_dns_record') }}"
    dns_zone: "{{ lookup('role_var', '_dns_zone') }}"
    dns_proxy: "{{ lookup('role_var', '_dns_proxy') }}"

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('role_var', '_metrics_dns_record') }}"
    dns_zone: "{{ lookup('role_var', '_metrics_dns_zone') }}"
    dns_proxy: "{{ lookup('role_var', '_metrics_dns_proxy') }}"
  when: lookup('role_var', '_metrics_enabled', role='traefik')

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Remove existing Error Pages Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    var_prefix: "error_pages"
  when: not traefik_error_pages_enabled

- name: Remove existing Authelia Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    var_prefix: "authelia"
  when: not authelia_is_master

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Traefik ZeroSSL Tasks
  ansible.builtin.include_tasks: "subtasks/zerossl.yml"
  when: traefik_enable_zerossl and (not continuous_integration)

- name: Traefik Config Tasks
  ansible.builtin.include_tasks: "subtasks/config.yml"

- name: Traefik Crowdsec Tasks
  ansible.builtin.include_tasks: "subtasks/crowdsec.yml"
  when: crowdsec_is_enabled

- name: Remove Certificates
  ansible.builtin.file:
    path: "{{ lookup('role_var', '_paths_location', role='traefik') }}/acme.json"
    state: absent
  when: ('traefik-reset-certs' in ansible_run_tags)

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Wait for 'acme.json' to be created
  ansible.builtin.wait_for:
    path: "{{ lookup('role_var', '_paths_acme_config_location', role='traefik') }}"
    state: present
  when: (not continuous_integration)

- name: Chown '{{ lookup('role_var', '_paths_location', role='traefik') }}'
  ansible.builtin.file:
    path: "{{ lookup('role_var', '_paths_location', role='traefik') }}"
    state: directory
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  when: (not continuous_integration)

- name: Chown '{{ lookup('role_var', '_paths_acme_config_location', role='traefik') }}'
  ansible.builtin.file:
    path: "{{ lookup('role_var', '_paths_acme_config_location', role='traefik') }}"
    state: file
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0600"
  when: (not continuous_integration)

- name: "Import Authelia Role"
  ansible.builtin.include_role:
    name: authelia
  when: lookup('role_var', '_authelia_enabled', role='traefik') and authelia_is_master

- name: "Import Authentik Role"
  ansible.builtin.include_role:
    name: authentik
  when: lookup('role_var', '_authentik_enabled', role='traefik') and authentik_is_master

- name: "Import Error Pages Role"
  ansible.builtin.include_role:
    name: error_pages
  when: traefik_error_pages_enabled
