#########################################################################
# Title:         Saltbox: Hetzner NFS Server Uninstall Task             #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check 'nfs_vlan.service' exists
  ansible.builtin.stat:
    path: '/etc/systemd/system/nfs_vlan.service'
  register: nfs_vlan_service

- name: Stop 'nfs_vlan.service'
  ansible.builtin.systemd_service:
    state: stopped
    name: nfs_vlan
    daemon_reload: true
    enabled: false
  when: nfs_vlan_service.stat.exists

- name: Uninstall nfs requirements
  ansible.builtin.apt:
    state: absent
    name:
      - rpcbind
      - nfs-kernel-server

- name: Remove files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/systemd/system/nfs_vlan.service"
    - "/etc/exports"
    - "/etc/hosts.deny"
    - "/opt/hetzner_nfs"

- name: Reboot message
  ansible.builtin.debug:
    msg:
      - "Restarting the server to apply changes..."

- name: Reboot
  ansible.builtin.shell: reboot

- name: Reboot message
  ansible.builtin.debug:
    msg:
      - "Failed to reboot automatically."
      - "You will need to restart the server yourself."
