#########################################################################
# Title:         Saltbox: Hetzner NFS Mount Task                        #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create nfs server directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  with_items:
    - /opt/hetzner_nfs
    - /mnt/feeder

- name: Import 'hosts.deny' file
  ansible.builtin.template:
    src: client/hosts.deny.j2
    dest: /etc/hosts.deny
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
    mode: "0644"
    force: true

- name: Import 'hosts.allow' file
  ansible.builtin.template:
    src: client/hosts.allow.j2
    dest: /etc/hosts.allow
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
    mode: "0644"
    force: true

- name: Install nfs requirements
  ansible.builtin.apt:
    state: present
    name:
      - rpcbind
      - nfs-common

- name: Import 'init_vlan.sh' file
  ansible.builtin.template:
    src: client/init_vlan.sh.j2
    dest: /opt/hetzner_nfs/init_vlan.sh
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
    mode: "0775"
    force: "{{ hetzner_nfs_init_overwrite_client }}"

- name: Check 'nfs_vlan.service' exists
  ansible.builtin.stat:
    path: '/etc/systemd/system/nfs_vlan.service'
  register: nfs_vlan_service

- name: Import 'nfs_vlan.service' file
  ansible.builtin.template:
    src: client/nfs_vlan.service.j2
    dest: /etc/systemd/system/nfs_vlan.service
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
    mode: "0644"
    force: true
  when: (not nfs_vlan_service.stat.exists)

- name: Start 'nfs_vlan.service'
  ansible.builtin.systemd:
    state: started
    name: nfs_vlan
    daemon_reload: true
    enabled: true

  # mergerfs edits

- name: Add 'After=init_vlan.service' to '{{ mergerfs_service_name }}'
  ansible.builtin.lineinfile:
    path: "/etc/systemd/system/{{ mergerfs_service_name }}"
    regexp: '(^After\=network-online\.target).*'
    line: '\1 init_vlan.service'
    state: present
    backrefs: yes
  when: mergerfs_service.stat.exists

- name: Replace '/mnt/local' with '/mnt/feeder' in '{{ mergerfs_service_name }}'
  ansible.builtin.replace:
    path: "/etc/systemd/system/{{ mergerfs_service_name }}"
    regexp: "\\/mnt\\/local"
    replace: '/mnt/feeder'
  when: mergerfs_service.stat.exists
