#########################################################################
# Title:         Saltbox: Plex Autoscan Role                            #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Import Services Task
  import_tasks: "subtasks/services.yml"

- name: Create plex_autoscan directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    recurse: yes
  with_items:
    - /opt/plex_autoscan

- name: Clone plex_autoscan repo 'HEAD'
  git:
    repo: https://github.com/saltyorg/plex_autoscan.git
    dest: /opt/plex_autoscan
    clone: true
    version: HEAD
    force: true
  become: true
  become_user: "{{ user.name }}"
  ignore_errors: true
  register: plex_autoscan_clone_status

- name: Clone plex_autoscan repo 'master'
  git:
    repo: https://github.com/saltyorg/plex_autoscan.git
    dest: /opt/plex_autoscan
    clone: true
    version: master
    force: true
  become: true
  become_user: "{{ user.name }}"
  when: plex_autoscan_clone_status is failed

- name: Install pip requirements
  pip:
    requirements: /opt/plex_autoscan/requirements.txt
    executable: pip3

- name: Set 'scan.py' as executable
  file:
    path: /opt/plex_autoscan/scan.py
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: a+x

- name: Import Settings Task
  import_tasks: "subtasks/settings.yml"

- name: Start 'plex_autoscan.service'
  systemd:
    name: plex_autoscan
    state: started
    enabled: true
    daemon_reload: true
