##########################################################################
# Title:         Saltbox: phpLDAPadmin | Default Variables               #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

phpldapadmin_name: "phpldapadmin"

################################
# Config
################################

phpldapadmin_mail_sender: "{{ user.email }}"

################################
# Web
################################

phpldapadmin_web_subdomain: "ldap"
phpldapadmin_web_domain: "{{ user.domain }}"
phpldapadmin_web_port: "80"
phpldapadmin_web_url: "{{ 'https://' + traefik_host }}"

################################
# DNS
################################

phpldapadmin_dns_record: "{{ phpldapadmin_web_subdomain }}"
phpldapadmin_dns_zone: "{{ phpldapadmin_web_domain }}"
phpldapadmin_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

phpldapadmin_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
phpldapadmin_traefik_middleware_default: "{{ traefik_default_middleware }}"
phpldapadmin_traefik_middleware_custom: ""
phpldapadmin_traefik_certresolver: "{{ traefik_default_certresolver }}"
phpldapadmin_traefik_enabled: true
phpldapadmin_traefik_api_enabled: false
phpldapadmin_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
phpldapadmin_docker_container: "{{ phpldapadmin_name }}"

# Image
phpldapadmin_docker_image_pull: true
phpldapadmin_docker_image_repo: "osixia/phpldapadmin"
phpldapadmin_docker_image_tag: "latest"
phpldapadmin_docker_image: "{{ phpldapadmin_docker_image_repo
                               + ':' + phpldapadmin_docker_image_tag }}"

# Ports
phpldapadmin_docker_ports_defaults: []
phpldapadmin_docker_ports_custom: []
phpldapadmin_docker_ports: "{{ phpldapadmin_docker_ports_defaults
                               + phpldapadmin_docker_ports_custom }}"

# Envs
phpldapadmin_docker_envs_default:
  TZ: "{{ tz }}"
  PHPLDAPADMIN_LDAP_HOSTS: "openldap"
  PHPLDAPADMIN_HTTPS: "false"
phpldapadmin_docker_envs_custom: {}
phpldapadmin_docker_envs: "{{ phpldapadmin_docker_envs_default
                              | combine(phpldapadmin_docker_envs_custom) }}"

# Commands
phpldapadmin_docker_commands_default: []
phpldapadmin_docker_commands_custom: []
phpldapadmin_docker_commands: "{{ phpldapadmin_docker_commands_default
                                  + phpldapadmin_docker_commands_custom }}"

# Volumes
phpldapadmin_docker_volumes_default: []
phpldapadmin_docker_volumes_custom: []
phpldapadmin_docker_volumes: "{{ phpldapadmin_docker_volumes_default
                                 + phpldapadmin_docker_volumes_custom }}"

# Devices
phpldapadmin_docker_devices_default: []
phpldapadmin_docker_devices_custom: []
phpldapadmin_docker_devices: "{{ phpldapadmin_docker_devices_default
                                 + phpldapadmin_docker_devices_custom }}"

# Hosts
phpldapadmin_docker_hosts_default: []
phpldapadmin_docker_hosts_custom: []
phpldapadmin_docker_hosts: "{{ docker_hosts_common
                               | combine(phpldapadmin_docker_hosts_default)
                               | combine(phpldapadmin_docker_hosts_custom) }}"

# Labels
phpldapadmin_docker_labels_default: {}
phpldapadmin_docker_labels_custom: {}
phpldapadmin_docker_labels: "{{ docker_labels_common
                                | combine(phpldapadmin_docker_labels_default)
                                | combine(phpldapadmin_docker_labels_custom) }}"

# Hostname
phpldapadmin_docker_hostname: "{{ phpldapadmin_name }}"

# Networks
phpldapadmin_docker_networks_alias: "{{ phpldapadmin_name }}"
phpldapadmin_docker_networks_default: []
phpldapadmin_docker_networks_custom: []
phpldapadmin_docker_networks: "{{ docker_networks_common
                                  + phpldapadmin_docker_networks_default
                                  + phpldapadmin_docker_networks_custom }}"

# Capabilities
phpldapadmin_docker_capabilities_default: []
phpldapadmin_docker_capabilities_custom: []
phpldapadmin_docker_capabilities: "{{ phpldapadmin_docker_capabilities_default
                                      + phpldapadmin_docker_capabilities_custom }}"

# Security Opts
phpldapadmin_docker_security_opts_default: []
phpldapadmin_docker_security_opts_custom: []
phpldapadmin_docker_security_opts: "{{ phpldapadmin_docker_security_opts_default
                                       + phpldapadmin_docker_security_opts_custom }}"

# Restart Policy
phpldapadmin_docker_restart_policy: unless-stopped

# State
phpldapadmin_docker_state: started
