#########################################################################
# Title:         Saltbox: Plex Role                                     #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Filter Plex Network Modes # noqa jinja[invalid]
  ansible.builtin.set_fact:
    plex_role_network_modes: "{{ plex_role_network_modes + [plex_lookup] }}"
  vars:
    plex_name: "{{ item }}"
    plex_lookup: "{{ lookup('role_var', '_docker_network_mode', role='plex', default=docker_networks_name_common) }}"
  loop: "{{ plex_instances }}"
  when: (plex_instances | length > 1) and ('container:' in plex_lookup)

- name: Fail if non-unique entries are present
  ansible.builtin.fail:
    msg: "At least two of your Plex instances are using the same 'container:' network_mode and this will not work due to port collision."
  when: (plex_instances | length > 1) and (plex_role_network_modes | length) != (plex_role_network_modes | unique | length)

- name: "Execute Plex roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    plex_name: "{{ instance }}"
  with_items: "{{ plex_instances }}"
  loop_control:
    loop_var: instance
