#########################################################################
# Title:         Saltbox: Rclone | Default Variables                    #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
rclone_latest_releases_url: "{{ svm }}https://api.github.com/repos/rclone/rclone/releases/latest"

rclone_latest_release_lookup_command: |
  curl -s {{ rclone_latest_releases_url }} \
    | jq -r ".assets[] |select(.name | test(\"linux-amd64.zip\")) \
    | .browser_download_url"
