#########################################################################
# Title:         Saltbox: User | Default Variables                      #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# User
user_paths_home_location: "/home/{{ user.name }}"
user_paths_home_saltbox_location: "/srv/git/saltbox"

# Overrides
# user_docker_group_id: <int>
# user_group_id: <int>
# user_id: <int>

# srv
srv_folder: "/srv"

# Saltbox
saltbox_git_repo_url: "https://github.com/saltyorg/Saltbox.git"
saltbox_git_repo_dest: "/srv/git/saltbox"
saltbox_git_repo_branch_primary: "master"
saltbox_git_repo_branch_secondary: "master"

# CB Scripts
sb_git_repo_url: "https://github.com/saltyorg/sb.git"
sb_git_repo_dest: "/srv/git/sb"
sb_git_repo_branch_primary: "master"
