#########################################################################
# Title:         Saltbox: Seerr Role                                    #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Seerr roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    seerr_name: "{{ instance }}"
  with_items: "{{ seerr_instances }}"
  loop_control:
    loop_var: instance
