#########################################################################
# Title:         Saltbox: Plex Autoscan | Services Task                 #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Services | Check if 'plex_autoscan.service' exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/plex_autoscan.service"
  register: plex_autoscan_service

- name: Services | Existing 'plex_autoscan.service' Tasks
  block:

    - name: Services | Populate Service Facts
      ansible.builtin.service_facts:

    - name: Services | Get 'plex_autoscan.service' state
      ansible.builtin.set_fact:
        plex_autoscan_service_running: "{{ (services['plex_autoscan.service'] is defined) and (services['plex_autoscan.service']['state'] == 'running') }}"

    - name: Services | Stop 'plex_autoscan.service'
      ansible.builtin.systemd:
        name: plex_autoscan
        state: stopped
      when: plex_autoscan_service_running

  when: plex_autoscan_service.stat.exists
