#########################################################################
# Title:         Saltbox: Plex Autoscan | Settings Task                 #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Settings | Install required packages
  ansible.builtin.apt:
    state: present
    name:
      - jq
      - moreutils

- name: Settings | Import Plex Auth Token role
  ansible.builtin.import_role:
    name: plex_auth_token
  when: plex_account_is_enabled

- name: Settings | Check if 'config.json' exists
  ansible.builtin.stat:
    path: "/opt/plex_autoscan/config/config.json"
  register: plex_autoscan_config

- name: Settings | New 'config.json' tasks
  block:

    - name: Settings | Generate 32 character 'SERVER_PASS'
      ansible.builtin.set_fact:
        plex_autoscan_server_pass: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"

    - name: Settings | Import default 'config.json'
      ansible.builtin.template:
        src: config.json.j2
        dest: /opt/plex_autoscan/config/config.json
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0775"
        force: true

  when: not plex_autoscan_config.stat.exists

- name: Settings | Existing 'config.json' tasks
  block:

    - name: Settings | Update 'PLEX_LD_LIBRARY_PATH' in 'config.json'
      ansible.builtin.shell: |
        CONFIG_PATH="/opt/plex_autoscan/config/config.json"
        jq '.PLEX_LD_LIBRARY_PATH = "/usr/lib/plexmediaserver/lib"' ${CONFIG_PATH} | sponge ${CONFIG_PATH}
      become: true
      become_user: "{{ user.name }}"

    - name: Settings | Update Plex URL in 'config.json'
      ansible.builtin.shell: |
        CONFIG_PATH="/opt/plex_autoscan/config/config.json"
        jq '.PLEX_LOCAL_URL = "https://plex.{{ user.domain }}"' ${CONFIG_PATH} | sponge ${CONFIG_PATH}
      become: true
      become_user: "{{ user.name }}"

    - name: Settings | Update Plex Token in 'config.json'
      ansible.builtin.shell: |
        CONFIG_PATH="/opt/plex_autoscan/config/config.json"
        jq '.PLEX_TOKEN = "{{ plex_auth_token | default('') }}"' ${CONFIG_PATH} | sponge ${CONFIG_PATH}
      become: true
      become_user: "{{ user.name }}"

  when: plex_autoscan_config.stat.exists

# Update 'config.json' for new and existing setups

- name: Settings | Upgrade 'config.json'
  ansible.builtin.shell: "{{ plex_autoscan_bin_folder }}/python3 /opt/plex_autoscan/scan.py update_config"
  become: true
  become_user: "{{ user.name }}"
  ignore_errors: true
